export const ATOPIC_DERMATITIS_KEYWORDS = [
  "atopic dermatitis", "atopic", "eczema", "ad", "atd",
  "iga", "viga", "easi", "easi-75", "easi-90", "easi-100",
  "pp-nrs", "wp-nrs", "pruritus", "itch", "tcs", "tci",
  "dupixent", "dupilumab", "adbry", "adtralza", "tralokinumab",
  "ebglyss", "lebrikizumab", "nemluvio", "nemolizumab",
  "rinvoq", "upadacitinib", "cibinqo", "abrocitinib",
  "olumiant", "baricitinib", "amlitelimab", "rocatinlimab",
  "galvokimig", "zumilokibart", "apg777", "apg279",
  "afimkibart", "rg6299", "soquelitinib", "tilrekimig", "ompekimig",
  "il-4", "il-4r", "il-4rα", "il-13", "il-31", "il-31ra",
  "jak", "jak1", "jak1/2", "ox40", "ox40l", "tl1a", "tslp", "il-33", "pf-07275315", "pfizer trispecific", "il-4 il-13 tslp", "ompekimig", "pf-07264660",
];

const pct = (value: number) => value;

const atopicDermatitis = {
  condition: "Atopic Dermatitis",
  dataRevisionDate: "2026-05-10",
  evidenceStandard:
    "Fact-checked against AtD_26.pptx and current prescribing information, labels, publications, sponsor press releases, and trial registry records available on 2026-05-10.",
  units: "All numeric efficacy values are percentages of randomized/eligible subjects unless otherwise stated.",
  primaryEndpoints: [
    "IGA 0/1 or vIGA-AD 0/1 with ≥2-point improvement",
    "EASI-75",
    "EASI-90",
    "PP-NRS ≥4-point improvement",
    "WP-NRS ≥4-point improvement",
  ],
  deckComparisonNotes: [
    "AtD_26 concomitant-TCS cheat-sheet charts generally plot placebo-adjusted deltas, not absolute active-arm rates. This file stores absolute active and comparator rates separately from placebo-adjusted delta metrics.",
    "Unverified longitudinal timepoints from the prior file were removed unless they were explicitly supported by a label, publication, or the deck.",
    "For abrocitinib, label-reported PP-NRS4 values are Week 2 early-itch values in the pivotal tables; they are not carried as Week 12 values.",
    "For emerging assets, exact efficacy values are included only when public sources disclosed them. Otherwise, status and readout notes are retained without invented numeric results.",
  ],
  tcsPhase3StudiesIncluded: [
    {
      drug: "dupilumab",
      brandName: "Dupixent",
      study: "LIBERTY AD CHRONOS",
      treatment: "dupilumab 300 mg Q2W + TCS",
      comparator: "placebo + TCS",
      timepoint: "Week 16",
      deckSlides: [32, 33, 39, 40, 42],
    },
    {
      drug: "tralokinumab",
      brandName: "Adbry / Adtralza",
      study: "ECZTRA 3",
      treatment: "tralokinumab 300 mg Q2W + TCS",
      comparator: "placebo + TCS",
      timepoint: "Week 16",
      deckSlides: [],
      note: "Added because it is an approved biologic Phase 3 concomitant-TCS study even though the provided deck emphasized other concomitant-TCS studies.",
    },
    {
      drug: "lebrikizumab",
      brandName: "Ebglyss",
      study: "ADhere",
      treatment: "lebrikizumab 500 mg loading at Weeks 0 and 2, then 250 mg Q2W + TCS",
      comparator: "placebo + TCS",
      timepoint: "Week 16",
      deckSlides: [32, 33, 39, 40, 42],
    },
    {
      drug: "nemolizumab",
      brandName: "Nemluvio",
      study: "ARCADIA 1",
      treatment: "nemolizumab 60 mg loading dose, then 30 mg Q4W + TCS/TCI",
      comparator: "placebo + TCS/TCI",
      timepoint: "Week 16",
      deckSlides: [32, 33, 39, 42],
    },
    {
      drug: "nemolizumab",
      brandName: "Nemluvio",
      study: "ARCADIA 2",
      treatment: "nemolizumab 60 mg loading dose, then 30 mg Q4W + TCS/TCI",
      comparator: "placebo + TCS/TCI",
      timepoint: "Week 16",
      deckSlides: [32, 33, 39, 42],
    },
    {
      drug: "upadacitinib",
      brandName: "Rinvoq",
      study: "AD Up / Trial AD-3",
      treatment: "upadacitinib 15 mg QD or 30 mg QD + TCS",
      comparator: "placebo + TCS",
      timepoint: "Week 16",
      deckSlides: [32, 33, 39, 40, 42],
    },
    {
      drug: "abrocitinib",
      brandName: "Cibinqo",
      study: "JADE COMPARE / Trial-AD-3",
      treatment: "abrocitinib 100 mg QD or 200 mg QD + background TCS",
      comparator: "placebo + background TCS; active dupilumab arm included in study design",
      timepoint: "Week 12 for IGA/EASI; Week 2 for PP-NRS4",
      deckSlides: [],
      note: "Added as an approved-drug Phase 3 concomitant-TCS study; not present in the deck cheat-sheet bars.",
    },
    {
      drug: "abrocitinib",
      brandName: "Cibinqo",
      study: "JADE TEEN / Trial-AD-4",
      treatment: "abrocitinib 100 mg QD or 200 mg QD + background TCS",
      comparator: "placebo + background TCS",
      timepoint: "Week 12 for IGA/EASI; Week 2 for PP-NRS4",
      deckSlides: [],
      note: "Adolescent approved-age concomitant-TCS pivotal study.",
    },
    {
      drug: "baricitinib",
      brandName: "Olumiant",
      study: "BREEZE-AD7",
      treatment: "baricitinib 2 mg QD or 4 mg QD + TCS",
      comparator: "placebo + TCS",
      timepoint: "Week 16",
      deckSlides: [],
      note: "EU/selected ex-US AD-approved JAK inhibitor; not FDA-approved for AD in the US.",
    },
  ],

  drugs: [
    {
      name: "dupilumab",
      brandName: "Dupixent",
      drugClass: "IL-4Rα antagonist",
      mechanism: "Blocks IL-4Rα, thereby inhibiting IL-4 and IL-13 signaling; subcutaneous maintenance dosing is every 2 or 4 weeks depending on age/weight.",
      route: "Subcutaneous",
      approvalYear: 2017,
      approvalRegion: "US/EU/global",
      approvedIndication:
        "Moderate-to-severe atopic dermatitis in adults and pediatric patients aged 6 months and older whose disease is not adequately controlled with topical prescription therapies or when those therapies are not advisable; may be used with or without topical corticosteroids.",
      primaryEndpointLabel: "IGA 0/1 and EASI-75 at Week 16",
      overallResult: pct(48),
      metrics: {
        "IGA 0/1": pct(37),
        "EASI-75": pct(48),
        "EASI-90": pct(33),
        "PP-NRS ≥4": pct(39),
      },
      trials: [
        {
          name: "SOLO 1",
          phase: "Phase 3",
          regimen: "dupilumab 300 mg Q2W",
          backgroundTherapy: "Monotherapy; topical rescue counted as nonresponse in primary efficacy analysis",
          comparator: "placebo",
          timepoint: "Week 16",
          n: 448,
          randomizedByArm: { dupilumab: 224, placebo: 224 },
          primaryEndpoint: "IGA 0/1 with ≥2-point improvement and EASI-75",
          result: pct(38),
          placeboResult: pct(10),
          allMetrics: { "IGA 0/1": pct(38), "EASI-75": pct(51), "EASI-90": pct(36), "PP-NRS ≥4": pct(41) },
          allPlaceboMetrics: { "IGA 0/1": pct(10), "EASI-75": pct(15), "EASI-90": pct(8), "PP-NRS ≥4": pct(12) },
          placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(28), "EASI-75": pct(36), "EASI-90": pct(28), "PP-NRS ≥4": pct(29) },
          publication: "Dupixent Prescribing Information, Table 12",
          year: 2017,
        },
        {
          name: "SOLO 2",
          phase: "Phase 3",
          regimen: "dupilumab 300 mg Q2W",
          backgroundTherapy: "Monotherapy; topical rescue counted as nonresponse in primary efficacy analysis",
          comparator: "placebo",
          timepoint: "Week 16",
          n: 469,
          randomizedByArm: { dupilumab: 233, placebo: 236 },
          primaryEndpoint: "IGA 0/1 with ≥2-point improvement and EASI-75",
          result: pct(36),
          placeboResult: pct(9),
          allMetrics: { "IGA 0/1": pct(36), "EASI-75": pct(44), "EASI-90": pct(30), "PP-NRS ≥4": pct(36) },
          allPlaceboMetrics: { "IGA 0/1": pct(9), "EASI-75": pct(12), "EASI-90": pct(7), "PP-NRS ≥4": pct(10) },
          placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(27), "EASI-75": pct(32), "EASI-90": pct(23), "PP-NRS ≥4": pct(26) },
          publication: "Dupixent Prescribing Information, Table 12",
          year: 2017,
        },
        {
          name: "CHRONOS",
          phase: "Phase 3",
          regimen: "dupilumab 300 mg Q2W + TCS",
          backgroundTherapy: "Concomitant TCS; TCI allowed for problem areas as clinically needed",
          comparator: "placebo + TCS",
          timepoint: "Week 16",
          n: 421,
          randomizedByArm: { dupilumabPlusTcs: 106, placeboPlusTcs: 315 },
          primaryEndpoint: "IGA 0/1 with ≥2-point improvement and EASI-75",
          result: pct(39),
          placeboResult: pct(12),
          allMetrics: { "IGA 0/1": pct(39), "EASI-75": pct(69), "EASI-90": pct(40), "PP-NRS ≥4": pct(59) },
          allPlaceboMetrics: { "IGA 0/1": pct(12), "EASI-75": pct(23), "EASI-90": pct(11), "PP-NRS ≥4": pct(20) },
          placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(27), "EASI-75": pct(46), "EASI-90": pct(29), "PP-NRS ≥4": pct(39) },
          deckConcomitantTcsDeltas: { "IGA 0/1": pct(27), "EASI-75": pct(46) },
          publication: "Dupixent Prescribing Information, Table 12; AtD_26 concomitant-TCS cheat sheets",
          year: 2017,
        },
      ],
      keyMessage: "Guideline-familiar first-line biologic cornerstone with broad pediatric indication and no boxed warning.",
      confidence: "high",
      safetyBullets: [
        "No boxed warning for JAK-class risks",
        "Conjunctivitis/keratitis and injection-site reactions are label-relevant adverse events",
        "No routine laboratory monitoring requirement in the label for AD",
      ],
      safetySignals: { BBW: "green", Malignancy: "green", Infection: "yellow", "CV Risk": "green", Monitoring: "green", "IBD Risk": "green" },
    },

    {
      name: "tralokinumab",
      brandName: "Adbry / Adtralza",
      drugClass: "IL-13 antagonist",
      mechanism: "Neutralizes IL-13; subcutaneous Q2W maintenance dosing after loading dose.",
      route: "Subcutaneous",
      approvalYear: 2021,
      approvalRegion: "US/EU/global",
      approvedIndication:
        "Moderate-to-severe atopic dermatitis in adults and pediatric patients aged 12 years and older whose disease is not adequately controlled with topical prescription therapies or when those therapies are not advisable; may be used with or without topical corticosteroids.",
      primaryEndpointLabel: "IGA 0/1 and EASI-75 at Week 16",
      overallResult: pct(29),
      metrics: {
        "IGA 0/1": pct(19),
        "EASI-75": pct(29),
        "Worst Daily Pruritus NRS ≥4": pct(23),
      },
      trials: [
        {
          name: "ECZTRA 1",
          phase: "Phase 3",
          regimen: "tralokinumab 300 mg Q2W",
          backgroundTherapy: "Monotherapy",
          comparator: "placebo",
          timepoint: "Week 16",
          n: 798,
          randomizedByArm: { tralokinumab: 601, placebo: 197 },
          primaryEndpoint: "IGA 0/1 and EASI-75",
          result: pct(16),
          placeboResult: pct(7),
          allMetrics: { "IGA 0/1": pct(16), "EASI-75": pct(25), "Worst Daily Pruritus NRS ≥4": pct(20) },
          allPlaceboMetrics: { "IGA 0/1": pct(7), "EASI-75": pct(13), "Worst Daily Pruritus NRS ≥4": pct(10) },
          placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(9), "EASI-75": pct(12), "Worst Daily Pruritus NRS ≥4": pct(10) },
          publication: "Adbry Prescribing Information, Table 2",
          year: 2021,
        },
        {
          name: "ECZTRA 2",
          phase: "Phase 3",
          regimen: "tralokinumab 300 mg Q2W",
          backgroundTherapy: "Monotherapy",
          comparator: "placebo",
          timepoint: "Week 16",
          n: 770,
          randomizedByArm: { tralokinumab: 577, placebo: 193 },
          primaryEndpoint: "IGA 0/1 and EASI-75",
          result: pct(21),
          placeboResult: pct(9),
          allMetrics: { "IGA 0/1": pct(21), "EASI-75": pct(33), "Worst Daily Pruritus NRS ≥4": pct(25) },
          allPlaceboMetrics: { "IGA 0/1": pct(9), "EASI-75": pct(10), "Worst Daily Pruritus NRS ≥4": pct(9) },
          placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(12), "EASI-75": pct(22), "Worst Daily Pruritus NRS ≥4": pct(16) },
          publication: "Adbry Prescribing Information, Table 2",
          year: 2021,
        },
        {
          name: "ECZTRA 3",
          phase: "Phase 3",
          regimen: "tralokinumab 300 mg Q2W + TCS",
          backgroundTherapy: "Concomitant mid-potency TCS as needed; lower-potency TCS or TCI could be used where mid-potency TCS was not advisable",
          comparator: "placebo + TCS",
          timepoint: "Week 16",
          n: 366,
          randomizedByArm: { tralokinumabPlusTcs: 243, placeboPlusTcs: 123 },
          primaryEndpoint: "IGA 0/1 and EASI-75",
          result: pct(38),
          placeboResult: pct(27),
          allMetrics: { "IGA 0/1": pct(38), "EASI-75": pct(56), "Worst Daily Pruritus NRS ≥4": pct(46) },
          allPlaceboMetrics: { "IGA 0/1": pct(27), "EASI-75": pct(37), "Worst Daily Pruritus NRS ≥4": pct(35) },
          placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(11), "EASI-75": pct(20), "Worst Daily Pruritus NRS ≥4": pct(11) },
          publication: "Adbry Prescribing Information, Table 2",
          year: 2021,
        },
      ],
      keyMessage: "IL-13-only biologic with approved use with or without TCS; ECZTRA 3 supplies the key approved-drug concomitant-TCS Phase 3 data.",
      confidence: "high",
      safetyBullets: [
        "No boxed warning",
        "Conjunctivitis and injection-site reactions are label-relevant events",
        "Helminth infection caution is included in class labeling",
      ],
      safetySignals: { BBW: "green", Malignancy: "green", Infection: "yellow", "CV Risk": "green", Monitoring: "green", "IBD Risk": "green" },
    },

    {
      name: "lebrikizumab",
      brandName: "Ebglyss",
      drugClass: "IL-13 antagonist",
      mechanism: "High-affinity IL-13 monoclonal antibody; subcutaneous Q2W induction with Q4W maintenance option after response.",
      route: "Subcutaneous",
      approvalYear: 2024,
      approvalRegion: "US 2024; EU 2023",
      approvedIndication:
        "Moderate-to-severe atopic dermatitis in adults and pediatric patients aged 12 years and older who weigh at least 40 kg, inadequately controlled with topical prescription therapies or when those therapies are not advisable; may be used with or without topical corticosteroids.",
      primaryEndpointLabel: "IGA 0/1 and EASI-75 at Week 16",
      overallResult: pct(56),
      metrics: {
        "IGA 0/1": pct(38),
        "EASI-75": pct(56),
        "EASI-90": pct(35),
        "Pruritus NRS ≥4": pct(43),
      },
      trials: [
        {
          name: "ADvocate 1",
          phase: "Phase 3",
          regimen: "lebrikizumab 500 mg at Weeks 0 and 2, then 250 mg Q2W",
          backgroundTherapy: "Monotherapy",
          comparator: "placebo",
          timepoint: "Week 16",
          n: 424,
          randomizedByArm: { lebrikizumab: 283, placebo: 141 },
          primaryEndpoint: "IGA 0/1 with ≥2-point improvement and EASI-75",
          result: pct(43),
          placeboResult: pct(13),
          allMetrics: { "IGA 0/1": pct(43), "EASI-75": pct(59), "EASI-90": pct(38), "Pruritus NRS ≥4": pct(46) },
          allPlaceboMetrics: { "IGA 0/1": pct(13), "EASI-75": pct(16), "EASI-90": pct(9), "Pruritus NRS ≥4": pct(13) },
          placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(30), "EASI-75": pct(42), "EASI-90": pct(29), "Pruritus NRS ≥4": pct(33) },
          publication: "Ebglyss Prescribing Information, Table 3",
          year: 2024,
        },
        {
          name: "ADvocate 2",
          phase: "Phase 3",
          regimen: "lebrikizumab 500 mg at Weeks 0 and 2, then 250 mg Q2W",
          backgroundTherapy: "Monotherapy",
          comparator: "placebo",
          timepoint: "Week 16",
          n: 427,
          randomizedByArm: { lebrikizumab: 281, placebo: 146 },
          primaryEndpoint: "IGA 0/1 with ≥2-point improvement and EASI-75",
          result: pct(33),
          placeboResult: pct(11),
          allMetrics: { "IGA 0/1": pct(33), "EASI-75": pct(52), "EASI-90": pct(31), "Pruritus NRS ≥4": pct(40) },
          allPlaceboMetrics: { "IGA 0/1": pct(11), "EASI-75": pct(18), "EASI-90": pct(10), "Pruritus NRS ≥4": pct(12) },
          placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(22), "EASI-75": pct(33), "EASI-90": pct(21), "Pruritus NRS ≥4": pct(28) },
          publication: "Ebglyss Prescribing Information, Table 3",
          year: 2024,
        },
        {
          name: "ADhere",
          phase: "Phase 3",
          regimen: "lebrikizumab 500 mg at Weeks 0 and 2, then 250 mg Q2W + TCS",
          backgroundTherapy: "Concomitant low- to mid-potency TCS; TCI allowed as needed in sensitive areas",
          comparator: "placebo + TCS",
          timepoint: "Week 16",
          n: 211,
          randomizedByArm: { lebrikizumabPlusTcs: 145, placeboPlusTcs: 66 },
          primaryEndpoint: "IGA 0/1 with ≥2-point improvement and EASI-75",
          result: pct(41.2),
          placeboResult: pct(22.1),
          allMetrics: { "IGA 0/1": pct(41.2), "EASI-75": pct(69.5), "EASI-90": pct(41.2), "Pruritus NRS ≥4": pct(50.6) },
          allPlaceboMetrics: { "IGA 0/1": pct(22.1), "EASI-75": pct(42.2), "EASI-90": pct(21.7), "Pruritus NRS ≥4": pct(31.9) },
          placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(18.3), "EASI-75": pct(26.4), "EASI-90": pct(18.9), "Pruritus NRS ≥4": pct(19.2) },
          deckConcomitantTcsDeltas: { "IGA 0/1": pct(18.3), "EASI-75": pct(26.4), "EASI-90": pct(18.9), "Pruritus NRS ≥4": pct(19.2) },
          publication: "JAMA Dermatology 2023 ADhere; AtD_26 concomitant-TCS cheat sheets",
          year: 2023,
        },
      ],
      keyMessage: "Approved IL-13 biologic; ADhere supplies pivotal concomitant-TCS Phase 3 data shown in the deck.",
      confidence: "high",
      safetyBullets: [
        "No boxed warning",
        "Conjunctivitis and keratitis are label-relevant class events",
        "Injection-site reactions and herpes zoster reported in the label",
      ],
      safetySignals: { BBW: "green", Malignancy: "green", Infection: "yellow", "CV Risk": "green", Monitoring: "green", "IBD Risk": "green" },
    },

    {
      name: "nemolizumab",
      brandName: "Nemluvio",
      drugClass: "IL-31RA antagonist",
      mechanism: "Blocks IL-31 receptor alpha signaling; subcutaneous Q4W after loading dose.",
      route: "Subcutaneous",
      approvalYear: 2024,
      approvalRegion: "Japan 2022; US 2024; EU 2025",
      approvedIndication:
        "Adults and pediatric patients 12 years and older with moderate-to-severe atopic dermatitis, in combination with topical corticosteroids and/or topical calcineurin inhibitors, when disease is not adequately controlled with topical prescription therapies.",
      primaryEndpointLabel: "IGA 0/1, EASI-75, and PP-NRS ≥4 at Week 16 with TCS/TCI",
      overallResult: pct(43),
      metrics: {
        "IGA 0/1": pct(37),
        "EASI-75": pct(43),
        "PP-NRS ≥4": pct(35),
      },
      trials: [
        {
          name: "ARCADIA 1",
          phase: "Phase 3",
          regimen: "nemolizumab 60 mg loading dose, then 30 mg Q4W + TCS/TCI",
          backgroundTherapy: "Concomitant TCS and/or TCI",
          comparator: "placebo + TCS/TCI",
          timepoint: "Week 16",
          n: 941,
          randomizedByArm: { nemolizumabPlusTcsTci: 620, placeboPlusTcsTci: 321 },
          primaryEndpoint: "IGA 0/1 and EASI-75; PP-NRS ≥4 key secondary endpoint",
          result: pct(36),
          placeboResult: pct(25),
          allMetrics: { "IGA 0/1": pct(36), "EASI-75": pct(44), "PP-NRS ≥4": pct(33) },
          allPlaceboMetrics: { "IGA 0/1": pct(25), "EASI-75": pct(29), "PP-NRS ≥4": pct(15) },
          placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(12), "EASI-75": pct(15), "PP-NRS ≥4": pct(18) },
          deckConcomitantTcsDeltas: { "IGA 0/1": pct(12), "EASI-75": pct(15), "PP-NRS ≥4": pct(18) },
          publication: "Nemluvio Prescribing Information, Table 4; AtD_26 concomitant-TCS cheat sheets",
          year: 2024,
        },
        {
          name: "ARCADIA 2",
          phase: "Phase 3",
          regimen: "nemolizumab 60 mg loading dose, then 30 mg Q4W + TCS/TCI",
          backgroundTherapy: "Concomitant TCS and/or TCI",
          comparator: "placebo + TCS/TCI",
          timepoint: "Week 16",
          n: 787,
          randomizedByArm: { nemolizumabPlusTcsTci: 522, placeboPlusTcsTci: 265 },
          primaryEndpoint: "IGA 0/1 and EASI-75; PP-NRS ≥4 key secondary endpoint",
          result: pct(38),
          placeboResult: pct(26),
          allMetrics: { "IGA 0/1": pct(38), "EASI-75": pct(42), "PP-NRS ≥4": pct(36) },
          allPlaceboMetrics: { "IGA 0/1": pct(26), "EASI-75": pct(30), "PP-NRS ≥4": pct(15) },
          placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(12), "EASI-75": pct(12), "PP-NRS ≥4": pct(21) },
          deckConcomitantTcsDeltas: { "IGA 0/1": pct(12), "EASI-75": pct(12), "PP-NRS ≥4": pct(21) },
          publication: "Nemluvio Prescribing Information, Table 4; AtD_26 concomitant-TCS cheat sheets",
          year: 2024,
        },
      ],
      keyMessage: "Approved IL-31RA biologic for itch-forward AD; pivotal AD label data are concomitant TCS/TCI studies, not monotherapy.",
      confidence: "high",
      safetyBullets: [
        "No boxed warning",
        "Headache, arthralgia, urticaria, and myalgia were more common than placebo in ARCADIA 1/2",
        "Herpes zoster and injection-site reactions are label-relevant adverse events",
      ],
      safetySignals: { BBW: "green", Malignancy: "green", Infection: "yellow", "CV Risk": "green", Monitoring: "green", "IBD Risk": "green" },
    },

    {
      name: "upadacitinib",
      brandName: "Rinvoq",
      drugClass: "Selective JAK1 inhibitor",
      mechanism: "Oral once-daily preferential JAK1 inhibitor.",
      route: "Oral",
      approvalYear: 2022,
      approvalRegion: "US/EU/global",
      approvedIndication:
        "Refractory moderate-to-severe atopic dermatitis in adults and pediatric patients 12 years and older not adequately controlled with other systemic drug products, including biologics, or when use of those therapies is inadvisable. Not recommended with other JAK inhibitors, biologic immunomodulators, or other immunosuppressants.",
      primaryEndpointLabel: "vIGA-AD 0/1 and EASI-75 at Week 16",
      overallResult: pct(72),
      metrics: {
        "vIGA-AD 0/1": pct(51),
        "EASI-75": pct(72),
        "EASI-90": pct(55),
        "WP-NRS ≥4": pct(60),
      },
      trials: [
        {
          name: "Measure Up 1 / Trial AD-1",
          phase: "Phase 3",
          regimen: "upadacitinib 15 mg or 30 mg QD",
          backgroundTherapy: "Monotherapy",
          comparator: "placebo",
          timepoint: "Week 16",
          n: 847,
          randomizedByArm: { placebo: 281, upadacitinib15mg: 281, upadacitinib30mg: 285 },
          primaryEndpoint: "vIGA-AD 0/1 and EASI-75",
          result: pct(48),
          placeboResult: pct(8),
          arms: [
            { dose: "15 mg QD", n: 281, allMetrics: { "vIGA-AD 0/1": pct(48), "EASI-75": pct(70), "EASI-90": pct(53), "EASI-100": pct(17), "WP-NRS ≥4": pct(52) }, placeboAdjustedDeltaMetrics: { "vIGA-AD 0/1": pct(40), "EASI-75": pct(53), "EASI-90": pct(45), "EASI-100": pct(15), "WP-NRS ≥4": pct(40) } },
            { dose: "30 mg QD", n: 285, allMetrics: { "vIGA-AD 0/1": pct(62), "EASI-75": pct(80), "EASI-90": pct(66), "EASI-100": pct(27), "WP-NRS ≥4": pct(60) }, placeboAdjustedDeltaMetrics: { "vIGA-AD 0/1": pct(54), "EASI-75": pct(63), "EASI-90": pct(58), "EASI-100": pct(25), "WP-NRS ≥4": pct(48) } },
          ],
          allPlaceboMetrics: { "vIGA-AD 0/1": pct(8), "EASI-75": pct(16), "EASI-90": pct(8), "EASI-100": pct(2), "WP-NRS ≥4": pct(12) },
          publication: "Rinvoq Prescribing Information, Table 15",
          year: 2021,
        },
        {
          name: "Measure Up 2 / Trial AD-2",
          phase: "Phase 3",
          regimen: "upadacitinib 15 mg or 30 mg QD",
          backgroundTherapy: "Monotherapy",
          comparator: "placebo",
          timepoint: "Week 16",
          n: 836,
          randomizedByArm: { placebo: 278, upadacitinib15mg: 276, upadacitinib30mg: 282 },
          primaryEndpoint: "vIGA-AD 0/1 and EASI-75",
          result: pct(39),
          placeboResult: pct(5),
          arms: [
            { dose: "15 mg QD", n: 276, allMetrics: { "vIGA-AD 0/1": pct(39), "EASI-75": pct(60), "EASI-90": pct(42), "EASI-100": pct(14), "WP-NRS ≥4": pct(42) }, placeboAdjustedDeltaMetrics: { "vIGA-AD 0/1": pct(34), "EASI-75": pct(47), "EASI-90": pct(37), "EASI-100": pct(13), "WP-NRS ≥4": pct(33) } },
            { dose: "30 mg QD", n: 282, allMetrics: { "vIGA-AD 0/1": pct(52), "EASI-75": pct(73), "EASI-90": pct(58), "EASI-100": pct(19), "WP-NRS ≥4": pct(60) }, placeboAdjustedDeltaMetrics: { "vIGA-AD 0/1": pct(47), "EASI-75": pct(60), "EASI-90": pct(53), "EASI-100": pct(18), "WP-NRS ≥4": pct(50) } },
          ],
          allPlaceboMetrics: { "vIGA-AD 0/1": pct(5), "EASI-75": pct(13), "EASI-90": pct(5), "EASI-100": pct(1), "WP-NRS ≥4": pct(9) },
          publication: "Rinvoq Prescribing Information, Table 15",
          year: 2021,
        },
        {
          name: "AD Up / Trial AD-3",
          phase: "Phase 3",
          regimen: "upadacitinib 15 mg or 30 mg QD + TCS",
          backgroundTherapy: "Concomitant TCS",
          comparator: "placebo + TCS",
          timepoint: "Week 16",
          n: 901,
          randomizedByArm: { placeboPlusTcs: 304, upadacitinib15mgPlusTcs: 300, upadacitinib30mgPlusTcs: 297 },
          primaryEndpoint: "vIGA-AD 0/1 and EASI-75",
          result: pct(40),
          placeboResult: pct(11),
          arms: [
            { dose: "15 mg QD + TCS", n: 300, allMetrics: { "vIGA-AD 0/1": pct(40), "EASI-75": pct(65), "EASI-90": pct(43), "EASI-100": pct(12), "WP-NRS ≥4": pct(52) }, placeboAdjustedDeltaMetrics: { "vIGA-AD 0/1": pct(29), "EASI-75": pct(38), "EASI-90": pct(30), "EASI-100": pct(11), "WP-NRS ≥4": pct(37) } },
            { dose: "30 mg QD + TCS", n: 297, allMetrics: { "vIGA-AD 0/1": pct(59), "EASI-75": pct(77), "EASI-90": pct(63), "EASI-100": pct(23), "WP-NRS ≥4": pct(64) }, placeboAdjustedDeltaMetrics: { "vIGA-AD 0/1": pct(48), "EASI-75": pct(51), "EASI-90": pct(50), "EASI-100": pct(21), "WP-NRS ≥4": pct(49) } },
          ],
          allPlaceboMetrics: { "vIGA-AD 0/1": pct(11), "EASI-75": pct(26), "EASI-90": pct(13), "EASI-100": pct(1), "WP-NRS ≥4": pct(15) },
          deckConcomitantTcsDeltas: { "vIGA-AD 0/1 15 mg": pct(29), "vIGA-AD 0/1 30 mg": pct(48), "EASI-75 15 mg": pct(38), "EASI-75 30 mg": pct(51), "EASI-90 15 mg": pct(30), "EASI-90 30 mg": pct(50), "WP-NRS ≥4 15 mg": pct(37), "WP-NRS ≥4 30 mg": pct(49) },
          publication: "Rinvoq Prescribing Information, Table 16; AtD_26 concomitant-TCS cheat sheets",
          year: 2021,
        },
      ],
      keyMessage: "High-efficacy oral option with JAK boxed warning and lab monitoring; Phase 3 concomitant-TCS AD Up data now included.",
      confidence: "high",
      safetyBullets: [
        "Boxed warning: serious infections, mortality, malignancy, major adverse cardiovascular events, and thrombosis",
        "Acne, herpes zoster, and laboratory abnormalities are dose-relevant considerations",
        "CBC, liver enzymes, lipids, and infection/TB screening are monitoring considerations",
      ],
      safetySignals: { BBW: "red", Malignancy: "yellow", Infection: "yellow", "CV Risk": "yellow", Monitoring: "red", "IBD Risk": "green" },
    },

    {
      name: "abrocitinib",
      brandName: "Cibinqo",
      drugClass: "Selective JAK1 inhibitor",
      mechanism: "Oral once-daily selective JAK1 inhibitor.",
      route: "Oral",
      approvalYear: 2022,
      approvalRegion: "US/EU/global",
      approvedIndication:
        "Refractory moderate-to-severe atopic dermatitis in adults and pediatric patients 12 years and older not adequately controlled with other systemic drug products, including biologics, or when use of those therapies is inadvisable. Not recommended with other JAK inhibitors, biologic immunomodulators, or other immunosuppressants.",
      primaryEndpointLabel: "IGA 0/1 and EASI-75 at Week 12",
      overallResult: pct(62),
      metrics: {
        "IGA 0/1": pct(41),
        "EASI-75": pct(62),
        "PP-NRS ≥4 at Week 2": pct(26),
      },
      trials: [
        {
          name: "JADE MONO-1 / Trial-AD-1",
          phase: "Phase 3",
          regimen: "abrocitinib 100 mg or 200 mg QD",
          backgroundTherapy: "Monotherapy",
          comparator: "placebo",
          timepoint: "Week 12 for IGA/EASI; Week 2 for PP-NRS4",
          n: 387,
          randomizedByArm: { placebo: 77, abrocitinib100mg: 156, abrocitinib200mg: 154 },
          primaryEndpoint: "IGA 0/1 and EASI-75",
          result: pct(44),
          placeboResult: pct(8),
          arms: [
            { dose: "100 mg QD", n: 156, allMetrics: { "IGA 0/1": pct(24), "EASI-75": pct(40), "PP-NRS ≥4 at Week 2": pct(11) }, placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(16), "EASI-75": pct(28), "PP-NRS ≥4 at Week 2": pct(9) } },
            { dose: "200 mg QD", n: 154, allMetrics: { "IGA 0/1": pct(44), "EASI-75": pct(62), "PP-NRS ≥4 at Week 2": pct(28) }, placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(36), "EASI-75": pct(51), "PP-NRS ≥4 at Week 2": pct(26) } },
          ],
          allPlaceboMetrics: { "IGA 0/1": pct(8), "EASI-75": pct(12), "PP-NRS ≥4 at Week 2": pct(2) },
          publication: "Cibinqo Prescribing Information, Table 9",
          year: 2021,
        },
        {
          name: "JADE MONO-2 / Trial-AD-2",
          phase: "Phase 3",
          regimen: "abrocitinib 100 mg or 200 mg QD",
          backgroundTherapy: "Monotherapy",
          comparator: "placebo",
          timepoint: "Week 12 for IGA/EASI; Week 2 for PP-NRS4",
          n: 391,
          randomizedByArm: { placebo: 78, abrocitinib100mg: 158, abrocitinib200mg: 155 },
          primaryEndpoint: "IGA 0/1 and EASI-75",
          result: pct(38),
          placeboResult: pct(9),
          arms: [
            { dose: "100 mg QD", n: 158, allMetrics: { "IGA 0/1": pct(28), "EASI-75": pct(44), "PP-NRS ≥4 at Week 2": pct(11) }, placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(19), "EASI-75": pct(33), "PP-NRS ≥4 at Week 2": pct(9) } },
            { dose: "200 mg QD", n: 155, allMetrics: { "IGA 0/1": pct(38), "EASI-75": pct(61), "PP-NRS ≥4 at Week 2": pct(24) }, placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(29), "EASI-75": pct(50), "PP-NRS ≥4 at Week 2": pct(22) } },
          ],
          allPlaceboMetrics: { "IGA 0/1": pct(9), "EASI-75": pct(10), "PP-NRS ≥4 at Week 2": pct(2) },
          publication: "Cibinqo Prescribing Information, Table 9",
          year: 2021,
        },
        {
          name: "JADE COMPARE / Trial-AD-3",
          phase: "Phase 3",
          regimen: "abrocitinib 100 mg or 200 mg QD + background TCS",
          backgroundTherapy: "Concomitant topical corticosteroids for all subjects",
          comparator: "placebo + TCS; dupilumab 300 mg Q2W active-reference arm was included in the design",
          timepoint: "Week 12 for IGA/EASI; Week 2 for PP-NRS4",
          n: 595,
          randomizedByArm: { placeboPlusTcs: 131, abrocitinib100mgPlusTcs: 238, abrocitinib200mgPlusTcs: 226 },
          primaryEndpoint: "IGA 0/1 and EASI-75",
          result: pct(47),
          placeboResult: pct(14),
          arms: [
            { dose: "100 mg QD + TCS", n: 238, allMetrics: { "IGA 0/1": pct(36), "EASI-75": pct(58), "PP-NRS ≥4 at Week 2": pct(14) }, placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(23), "EASI-75": pct(32), "PP-NRS ≥4 at Week 2": pct(6) } },
            { dose: "200 mg QD + TCS", n: 226, allMetrics: { "IGA 0/1": pct(47), "EASI-75": pct(68), "PP-NRS ≥4 at Week 2": pct(30) }, placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(34), "EASI-75": pct(41), "PP-NRS ≥4 at Week 2": pct(22) } },
          ],
          allPlaceboMetrics: { "IGA 0/1": pct(14), "EASI-75": pct(27), "PP-NRS ≥4 at Week 2": pct(8) },
          publication: "Cibinqo Prescribing Information, Table 10",
          year: 2021,
          note: "Active dupilumab comparator was part of the design; this file does not infer head-to-head superiority unless supported by a specific endpoint/source.",
        },
        {
          name: "JADE TEEN / Trial-AD-4",
          phase: "Phase 3",
          regimen: "abrocitinib 100 mg or 200 mg QD + background TCS in adolescents",
          backgroundTherapy: "Concomitant topical corticosteroids",
          comparator: "placebo + TCS",
          timepoint: "Week 12 for IGA/EASI; Week 2 for PP-NRS4",
          n: 284,
          randomizedByArm: { placeboPlusTcs: 95, abrocitinib100mgPlusTcs: 95, abrocitinib200mgPlusTcs: 94 },
          primaryEndpoint: "IGA 0/1 and EASI-75",
          result: pct(46),
          placeboResult: pct(24),
          arms: [
            { dose: "100 mg QD + TCS", n: 95, allMetrics: { "IGA 0/1": pct(39), "EASI-75": pct(64), "PP-NRS ≥4 at Week 2": pct(13) }, placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(15), "EASI-75": pct(23), "PP-NRS ≥4 at Week 2": pct(5) } },
            { dose: "200 mg QD + TCS", n: 94, allMetrics: { "IGA 0/1": pct(46), "EASI-75": pct(71), "PP-NRS ≥4 at Week 2": pct(25) }, placeboAdjustedDeltaMetrics: { "IGA 0/1": pct(21), "EASI-75": pct(29), "PP-NRS ≥4 at Week 2": pct(17) } },
          ],
          allPlaceboMetrics: { "IGA 0/1": pct(24), "EASI-75": pct(41), "PP-NRS ≥4 at Week 2": pct(8) },
          publication: "Cibinqo Prescribing Information, Table 11",
          year: 2021,
        },
      ],
      keyMessage: "Corrected to once-daily oral dosing; approved-drug Phase 3 concomitant-TCS data from JADE COMPARE and JADE TEEN are now included.",
      confidence: "high",
      safetyBullets: [
        "Boxed warning: serious infections, mortality, malignancy, major adverse cardiovascular events, and thrombosis",
        "Transient platelet decreases and nausea are notable dose-related considerations",
        "CBC and other baseline/ongoing lab monitoring are required per label",
      ],
      safetySignals: { BBW: "red", Malignancy: "yellow", Infection: "yellow", "CV Risk": "yellow", Monitoring: "red", "IBD Risk": "green" },
    },

    {
      name: "baricitinib",
      brandName: "Olumiant",
      drugClass: "JAK1/JAK2 inhibitor",
      mechanism: "Oral once-daily JAK1/JAK2 inhibitor.",
      route: "Oral",
      approvalYear: 2020,
      approvalRegion: "EU and selected ex-US markets for AD; not US FDA-approved for AD",
      approvedIndication:
        "EMA indication: moderate-to-severe atopic dermatitis in adult and pediatric patients 2 years of age and older who are candidates for systemic therapy.",
      primaryEndpointLabel: "vIGA-AD 0/1 at Week 16",
      overallResult: pct(31),
      metrics: {
        "vIGA-AD 0/1": pct(31),
        "EASI-75": pct(48),
        "EASI-90": pct(24),
        "Itch NRS ≥4": pct(44),
      },
      trials: [
        {
          name: "BREEZE-AD1",
          phase: "Phase 3",
          regimen: "baricitinib 2 mg or 4 mg QD",
          backgroundTherapy: "Monotherapy",
          comparator: "placebo",
          timepoint: "Week 16",
          primaryEndpoint: "vIGA-AD 0/1",
          result: pct(17),
          placeboResult: pct(5),
          arms: [
            { dose: "2 mg QD", allMetrics: { "vIGA-AD 0/1": pct(11) }, placeboAdjustedDeltaMetrics: { "vIGA-AD 0/1": pct(6) } },
            { dose: "4 mg QD", allMetrics: { "vIGA-AD 0/1": pct(17) }, placeboAdjustedDeltaMetrics: { "vIGA-AD 0/1": pct(12) } },
          ],
          allPlaceboMetrics: { "vIGA-AD 0/1": pct(5) },
          publication: "EMA EPAR summary / BREEZE-AD program",
          year: 2020,
        },
        {
          name: "BREEZE-AD2",
          phase: "Phase 3",
          regimen: "baricitinib 2 mg or 4 mg QD",
          backgroundTherapy: "Monotherapy",
          comparator: "placebo",
          timepoint: "Week 16",
          primaryEndpoint: "vIGA-AD 0/1",
          result: pct(14),
          placeboResult: pct(5),
          arms: [
            { dose: "2 mg QD", allMetrics: { "vIGA-AD 0/1": pct(11) }, placeboAdjustedDeltaMetrics: { "vIGA-AD 0/1": pct(6) } },
            { dose: "4 mg QD", allMetrics: { "vIGA-AD 0/1": pct(14) }, placeboAdjustedDeltaMetrics: { "vIGA-AD 0/1": pct(9) } },
          ],
          allPlaceboMetrics: { "vIGA-AD 0/1": pct(5) },
          publication: "EMA EPAR summary / BREEZE-AD program",
          year: 2020,
        },
        {
          name: "BREEZE-AD7",
          phase: "Phase 3",
          regimen: "baricitinib 2 mg or 4 mg QD + TCS",
          backgroundTherapy: "Concomitant TCS",
          comparator: "placebo + TCS",
          timepoint: "Week 16",
          n: 329,
          randomizedByArm: { placeboPlusTcs: 109, baricitinib2mgPlusTcs: 109, baricitinib4mgPlusTcs: 111 },
          primaryEndpoint: "vIGA-AD 0/1",
          result: pct(31),
          placeboResult: pct(15),
          arms: [
            { dose: "2 mg QD + TCS", n: 109, allMetrics: { "vIGA-AD 0/1": pct(24), "EASI-75": pct(43), "EASI-90": pct(17), "Itch NRS ≥4": pct(38) }, placeboAdjustedDeltaMetrics: { "vIGA-AD 0/1": pct(9), "EASI-75": pct(20), "EASI-90": pct(3), "Itch NRS ≥4": pct(18) } },
            { dose: "4 mg QD + TCS", n: 111, allMetrics: { "vIGA-AD 0/1": pct(31), "EASI-75": pct(48), "EASI-90": pct(24), "Itch NRS ≥4": pct(44) }, placeboAdjustedDeltaMetrics: { "vIGA-AD 0/1": pct(16), "EASI-75": pct(25), "EASI-90": pct(10), "Itch NRS ≥4": pct(24) } },
          ],
          allPlaceboMetrics: { "vIGA-AD 0/1": pct(15), "EASI-75": pct(23), "EASI-90": pct(14), "Itch NRS ≥4": pct(20) },
          publication: "BREEZE-AD7 Phase 3 publication; EMA EPAR",
          year: 2020,
          note: "Corrects prior file's implication of broad US AD approval; AD indication is EU/selected ex-US, not US FDA AD approval.",
        },
      ],
      keyMessage: "Regional AD-approved oral JAK1/2 inhibitor; not a US FDA AD approval. Concomitant-TCS Phase 3 BREEZE-AD7 data are included.",
      confidence: "high",
      safetyBullets: [
        "JAK-class safety concerns apply, including infection, thrombosis, malignancy, and MACE considerations",
        "Monitoring requirements and risk stratification are important",
        "Pulmonary embolism was reported in the 4 mg arm in BREEZE-AD7",
      ],
      safetySignals: { BBW: "red", Malignancy: "yellow", Infection: "yellow", "CV Risk": "yellow", Monitoring: "red", "IBD Risk": "green" },
    },
  ],

  emerging: [
    {
      name: "amlitelimab",
      sponsor: "Sanofi",
      drugClass: "Non-depleting anti-OX40L monoclonal antibody",
      mechanism: "Selective OX40 ligand blockade designed to modulate T-cell co-stimulation without depleting T cells.",
      route: "Subcutaneous",
      status: "Phase 3; not approved",
      latestReadout: "COAST 1, COAST 2, and SHORE Phase 3 data presented at AAD 2026; SHORE is the concomitant topical-therapy Phase 3 study.",
      trialProgram: ["COAST 1", "COAST 2", "SHORE"],
      tcsStudy: {
        study: "SHORE",
        phase: "Phase 3",
        backgroundTherapy: "TCS with or without TCI",
        timepoint: "Week 24",
        note: "Deck includes SHORE bars for concomitant topical therapy; regulatory approval not established.",
      },
      safetyNotes: ["The deck flags one cutaneous Kaposi sarcoma case in the OX40/OX40L class context; continue to treat as an emerging safety question."],
      confidence: "medium-high",
      sourceNotes: ["AtD_26 deck", "Sanofi AAD 2026 press release"],
    },
    {
      name: "rocatinlimab",
      sponsor: "Kyowa Kirin / Amgen",
      drugClass: "Anti-OX40 monoclonal antibody",
      mechanism: "Targets OX40, a T-cell co-stimulatory receptor.",
      route: "Subcutaneous",
      status: "Discontinued/terminated clinical program as of March 2026; not approved",
      latestReadout: "All ongoing clinical trials discontinued after a planned safety update; concerns included Kaposi sarcoma and other malignancies with possible viral or immune-related links.",
      trialProgram: ["ROCKET program"],
      tcsStudy: {
        study: "SHUTTLE",
        phase: "Phase 3",
        backgroundTherapy: "Concomitant TCS/TCI per deck",
        note: "Deck had included SHUTTLE as a Phase 3 concomitant-TCS study, but the rocatinlimab program was subsequently discontinued.",
      },
      confidence: "high",
      sourceNotes: ["AtD_26 deck", "Kyowa Kirin March 2026 discontinuation notice"],
    },
    {
      name: "galvokimig",
      sponsor: "UCB",
      drugClass: "IL-13 × IL-17A/F multispecific antibody-based therapeutic",
      mechanism: "Designed to inhibit IL-13, IL-17A, and IL-17F with extended half-life through albumin binding.",
      route: "Intravenous in first-in-patient study; subsequent route/regimen per ongoing trials",
      status: "Phase 2b; not approved",
      latestReadout: "Phase 1/2a first-in-patient data showed Week 12 EASI-75 and EASI-90 separation; Phase 2b dose-ranging trial initiated/expected around late 2025-2026.",
      metrics: { "EASI-75 Week 12": pct(64.9), "EASI-75 placebo Week 12": pct(12.3), "EASI-90 Week 12": pct(46.6), "EASI-90 placebo Week 12": pct(3.5) },
      confidence: "medium",
      sourceNotes: ["AtD_26 deck", "UCB EADV 2025 press release"],
    },
    {
      name: "zumilokibart",
      aliases: ["APG777"],
      sponsor: "Apogee Therapeutics",
      drugClass: "Half-life-extended anti-IL-13 monoclonal antibody",
      mechanism: "IL-13 blockade optimized for infrequent maintenance dosing.",
      route: "Subcutaneous",
      status: "Phase 2; planned Phase 3 initiation in 2026 pending further data; not approved",
      latestReadout: "APEX Part A positive 16-week data; Part B higher-exposure readout expected in 2026.",
      metrics: { "EASI-75 Week 16": pct(66.9), "EASI-75 placebo-adjusted Week 16": pct(42.5), "EASI percent decrease Week 16": pct(71.0) },
      confidence: "medium",
      sourceNotes: ["AtD_26 deck", "Apogee July 2025 APEX Part A press release"],
    },
    {
      name: "afimkibart",
      aliases: ["RG6299", "RO7790121"],
      sponsor: "Roche / Genentech",
      drugClass: "TL1A-targeted antibody",
      mechanism: "Targets TL1A/DR3 pathway biology; being studied in moderate-to-severe AD.",
      route: "Subcutaneous or intravenous per protocol",
      status: "Phase 2 recruiting; not approved",
      latestReadout: "Phase 2 trial started in 2025 with planned 2026 readout/completion window per registry/deck.",
      confidence: "medium",
      sourceNotes: ["AtD_26 deck", "ClinicalTrials.gov NCT06863961"],
    },
    {
      name: "APG279",
      sponsor: "Apogee Therapeutics",
      drugClass: "Combination/bispecific strategy targeting IL-13 and OX40L",
      mechanism: "Combines APG777 anti-IL-13 with APG990 anti-OX40L for dual Type 2 and broader T-cell co-stimulation modulation.",
      route: "Subcutaneous",
      status: "Phase 1b head-to-head versus dupilumab; not approved",
      latestReadout: "First patient dosed in Phase 1b head-to-head trial vs Dupixent; readout expected in 2H 2026 per sponsor.",
      confidence: "medium",
      sourceNotes: ["AtD_26 deck", "Apogee July 2025 press release/pipeline"],
    },
    {
      name: "soquelitinib",
      sponsor: "Corvus Pharmaceuticals",
      drugClass: "Oral ITK inhibitor",
      mechanism: "Targets interleukin-2-inducible T-cell kinase (ITK), a T-cell signaling kinase.",
      route: "Oral",
      status: "Phase 2 SIERRA1; not approved",
      latestReadout: "Phase 2 randomized placebo-controlled SIERRA1 in moderate-to-severe AD initiated/planned in 2026 with estimated primary completion in 2027.",
      confidence: "medium",
      sourceNotes: ["AtD_26 deck", "ClinicalTrials.gov NCT07441395", "Corvus Phase 1 AD updates"],
    },
    {
      name: "tilrekimig",
      aliases: ["PF-07275315"],
      sponsor: "Pfizer",
      drugClass: "IL-4 × IL-13 × TSLP trispecific antibody",
      mechanism: "Simultaneously targets IL-4, IL-13, and thymic stromal lymphopoietin.",
      route: "Subcutaneous; once-monthly regimen under study",
      status: "Positive Phase 2 topline; Phase 3 planning/acceleration; not approved",
      latestReadout: "March 2026 Pfizer topline: Phase 2 met primary EASI-75 endpoint at Week 16 across all tested monthly doses.",
      placeboAdjustedDeltaMetrics: { "EASI-75 low dose Week 16": pct(38.7), "EASI-75 middle dose Week 16": pct(51.9), "EASI-75 high dose Week 16": pct(49.4) },
      confidence: "medium-high",
      sourceNotes: ["AtD_26 deck", "Pfizer March 2026 topline press release"],
      keyInsight: "Pfizer's tilrekimig (PF-07275315) is an IL-4/IL-13/TSLP trispecific antibody — distinct from ompekimig (IL-4/IL-13/IL-33). Phase 2 met primary EASI-75 endpoint; placebo-adjusted deltas range from 38.7% to 51.9% across monthly doses at Week 16. Phase 3 planning underway.",
    },
    {
      name: "ompekimig",
      aliases: ["PF-07264660"],
      sponsor: "Pfizer",
      drugClass: "IL-4 × IL-13 × IL-33 trispecific antibody",
      mechanism: "Simultaneously targets IL-4, IL-13, and IL-33.",
      route: "Subcutaneous; regimen under study",
      status: "Phase 2; not approved",
      latestReadout: "Included in the same ongoing Pfizer Phase 2 program; Stage 1 high-dose ompekimig arm met the study primary endpoint per Pfizer/Fierce coverage, with additional dose-ranging ongoing.",
      confidence: "medium",
      sourceNotes: ["AtD_26 deck", "Pfizer March 2026 release and ClinicalTrials.gov NCT05995964"],
      keyInsight: "Pfizer's ompekimig (PF-07264660) is an IL-4/IL-13/IL-33 trispecific — distinct from tilrekimig (IL-4/IL-13/TSLP). Stage 1 high-dose arm met primary endpoint; additional dose-ranging ongoing.",
    },
    {
      name: "JNJ-95475939",
      aliases: ["JNJ-5939"],
      sponsor: "Johnson & Johnson / Janssen",
      drugClass: "IL-4Rα × IL-31 bispecific antibody",
      mechanism: "Designed to combine Type 2 pathway blockade with IL-31 itch-axis modulation.",
      route: "Subcutaneous",
      status: "Phase 2b DUPLEX-AD terminated early in December 2025; not approved",
      latestReadout: "Planned interim analysis met prespecified early termination criteria because the study did not meet J&J's high-bar efficacy threshold for AD advancement; JNJ reported it was well tolerated.",
      confidence: "high",
      sourceNotes: ["AtD_26 deck", "Johnson & Johnson December 2025 statement"],
    },
  ],

  correctionsApplied: [
    "Added missing approved-drug Phase 3 concomitant-TCS studies: CHRONOS, ECZTRA 3, ADhere, ARCADIA 1, ARCADIA 2, AD Up/Trial AD-3, JADE COMPARE/Trial-AD-3, JADE TEEN/Trial-AD-4, and BREEZE-AD7.",
    "Separated absolute response rates from placebo-adjusted deltas so deck bars are not mistaken for active-arm percentages.",
    "Corrected abrocitinib mechanism/dosing from twice-daily to once-daily and changed label-reported PP-NRS4 values to Week 2.",
    "Corrected baricitinib AD status to EU/selected ex-US markets and not US FDA-approved for AD.",
    "Corrected nemolizumab ARCADIA 1/2 values and indication: AD approval is in combination with TCS and/or TCI.",
    "Corrected lebrikizumab US approval timing/label framing and added ADhere with TCS values.",
    "Removed unsupported Week 24/52 timepoint data from pivotal induction trials unless explicitly sourced.",
    "Fixed emerging-pipeline sponsor/MoA/status errors and removed fabricated numeric results where public details were not available.",
    "Fixed the TypeScript syntax error in the prior tilrekimig dose object by rewriting the emerging section.",
  ],
} as const;

export default atopicDermatitis;
