export const HIDRADENITIS_SUPPURATIVA_KEYWORDS = [
  "hidradenitis suppurativa", "hidradenitis", "hs", "acne inversa", "hiscr", "hiscr50", "hiscr75", "hiscr90", "hiscr100",
  "ihs4", "ihs4-55", "abscess", "nodule", "draining tunnel", "sinus tract", "skin pain", "pioneer",
  "humira", "adalimumab", "cosentyx", "secukinumab", "bimzelx", "bimekizumab",
  "povorcitinib", "stop-hs", "sonelokimab", "vela", "lutikizumab", "intrepid", "upadacitinib", "rinvoq",
  "brivekimig", "nav-240", "nav-242", "sar445399", "il-17", "il-17a", "il-17f", "tnf", "jak1", "il-1", "ox40l",
];

const pct = (value: number) => value;

const hidradenitisSuppurativa = {
  condition: "Hidradenitis Suppurativa",
  dataRevisionDate: "2026-05-10",
  evidenceStandard:
    "Built from FDA labels/prescribing information, pivotal Phase 3 publications, AAD.pptx, ClinicalTrials.gov-style program details, and recent sponsor press releases available on 2026-05-10.",
  units: "All response values are percentages unless otherwise stated. Cross-trial comparisons are descriptive only because designs, baseline disease, biologic exposure, and endpoint rules differ.",
  endpointDefinitions: {
    HiSCR50:
      "At least 50% reduction from baseline in total abscess and inflammatory nodule count, with no increase in abscess count and no increase in draining tunnel count.",
    HiSCR75:
      "At least 75% reduction from baseline in total abscess and inflammatory nodule count, with no increase in abscess count and no increase in draining tunnel count.",
    HiSCR90:
      "At least 90% reduction from baseline in total abscess and inflammatory nodule count, with no increase in abscess count and no increase in draining tunnel count.",
    HiSCR100:
      "100% reduction from baseline in total abscess and inflammatory nodule count, with no increase in abscess count and no increase in draining tunnel count.",
    IHS4:
      "International Hidradenitis Suppurativa Severity Score System = inflammatory nodules x 1 + abscesses x 2 + draining tunnels x 4. AAD deck notes: <=3 mild, 4-10 moderate, >=11 severe.",
    IHS455:
      "Dichotomous IHS4-55 response = greater than 55% reduction from baseline in IHS4; increasingly used in trials and discussed in AAD deck.",
  },
  primaryEndpoints: ["HiSCR50", "HiSCR75", "HiSCR90", "HiSCR100", "IHS4-55", "Skin Pain NRS30"],
  deckComparisonNotes: [
    "AAD.pptx HS slides emphasize cross-trial caveats. This file keeps label-supported pivotal values separate from AAD cross-trial and late-stage pipeline values.",
    "AAD slide 8 compares observed-case long-term HiSCR75/90/100 values across secukinumab, bimekizumab, and povorcitinib at Week 48-54; those values are stored under aad2026Updates rather than used as head-to-head rankings.",
    "AAD slides 10-13 focus on TNF-alpha-experienced subgroups and should not be interpreted as all-comer efficacy.",
  ],

  drugs: [
    {
      name: "adalimumab",
      brandName: "Humira",
      biosimilarsAvailable: true,
      drugClass: "TNF-alpha inhibitor",
      mechanism: "Binds TNF-alpha and blocks its interaction with p55/p75 TNF receptors.",
      route: "Subcutaneous",
      approvalYear: 2015,
      approvedIndication:
        "US: moderate-to-severe hidradenitis suppurativa in patients 12 years of age and older.",
      adultHsDose:
        "160 mg on Day 1, 80 mg on Day 15, then 40 mg every week or 80 mg every other week starting Day 29 depending on product label/version and clinical use.",
      primaryEndpointLabel: "HiSCR50 at Week 12",
      overallResult: pct(50),
      metrics: { "HiSCR50": pct(50), "HiSCR75": null, "HiSCR90": null, "HiSCR100": null, "IHS4-55": null },
      pivotalStudies: [
        {
          name: "PIONEER I",
          phase: "Phase 3",
          n: 307,
          comparator: "placebo",
          regimen: "adalimumab 40 mg weekly after loading",
          primaryEndpoint: "HiSCR50 at Week 12",
          timepoint: "Week 12",
          result: pct(41.8),
          placeboResult: pct(26.0),
          placeboAdjustedDelta: pct(15.8),
          backgroundAntibiotics: "Not allowed during Period A in the pivotal design.",
          publication: "PIONEER I/II publication; Humira Prescribing Information",
          year: 2016,
        },
        {
          name: "PIONEER II",
          phase: "Phase 3",
          n: 326,
          comparator: "placebo",
          regimen: "adalimumab 40 mg weekly after loading",
          primaryEndpoint: "HiSCR50 at Week 12",
          timepoint: "Week 12",
          result: pct(58.9),
          placeboResult: pct(27.6),
          placeboAdjustedDelta: pct(31.3),
          backgroundAntibiotics: "Stable oral antibiotics were allowed in the study design.",
          publication: "PIONEER I/II publication; Humira Prescribing Information",
          year: 2016,
        },
      ],
      keyMessage: "First biologic benchmark for HS; now older efficacy benchmark with biosimilar competition and broad real-world familiarity.",
      confidence: "high",
      safetyBullets: ["Boxed warning for serious infections and malignancy", "Screen for TB and hepatitis B risk", "Avoid live vaccines", "Monitor for demyelinating disease, heart failure, lupus-like syndrome, and cytopenias"],
      safetySignals: { BBW: "red", Infection: "red", Malignancy: "yellow", TB: "red", Monitoring: "yellow", IBD: "green" },
      sourceNotes: ["Humira FDA label", "PIONEER I/II Phase 3 publication"],
    },
    {
      name: "secukinumab",
      brandName: "Cosentyx",
      drugClass: "IL-17A inhibitor",
      mechanism: "Human monoclonal antibody that binds IL-17A and inhibits IL-17A-mediated inflammatory signaling.",
      route: "Subcutaneous",
      approvalYear: 2023,
      approvedIndication:
        "US: moderate-to-severe hidradenitis suppurativa in adults and pediatric patients 12 years of age and older; pediatric expansion announced March 2026.",
      adultHsDose:
        "300 mg SC at Weeks 0, 1, 2, 3, and 4, then every 4 weeks; if inadequate response, consider every 2 weeks per label.",
      primaryEndpointLabel: "HiSCR50 at Week 16",
      overallResult: pct(44),
      metrics: { "HiSCR50 Q4W label range": "41.3-42.5", "HiSCR50 Q2W label range": "38.3-44.5", "HiSCR75 Week 52 observed-case range": "40-44", "HiSCR90 Week 52 observed-case range": "25-27", "HiSCR100 Week 52 observed-case range": "18-19", "IHS4-55": null },
      pivotalStudies: [
        {
          name: "SUNSHINE",
          phase: "Phase 3",
          n: 541,
          comparator: "placebo",
          regimen: "secukinumab 300 mg Q2W or Q4W after weekly loading",
          primaryEndpoint: "HiSCR50 at Week 16",
          timepoint: "Week 16",
          result: pct(44.5),
          placeboResult: pct(29.4),
          placeboAdjustedDelta: pct(15.1),
          arms: [
            { dose: "300 mg Q4W", allMetrics: { "HiSCR50": pct(41.3) }, placeboAdjustedDeltaMetrics: { "HiSCR50": pct(11.9) } },
            { dose: "300 mg Q2W", allMetrics: { "HiSCR50": pct(44.5) }, placeboAdjustedDeltaMetrics: { "HiSCR50": pct(15.1) } },
          ],
          allPlaceboMetrics: { "HiSCR50": pct(29.4) },
          note: "FDA-requested Week 16 analysis: Q2W was significant in SUNSHINE; Q4W was numerically higher than placebo but statistical interpretation differs by analysis hierarchy.",
          publication: "SUNSHINE/SUNRISE Phase 3 publication; Cosentyx Prescribing Information",
          year: 2023,
        },
        {
          name: "SUNRISE",
          phase: "Phase 3",
          n: 543,
          comparator: "placebo",
          regimen: "secukinumab 300 mg Q2W or Q4W after weekly loading",
          primaryEndpoint: "HiSCR50 at Week 16",
          timepoint: "Week 16",
          result: pct(42.5),
          placeboResult: pct(26.1),
          placeboAdjustedDelta: pct(16.4),
          arms: [
            { dose: "300 mg Q4W", allMetrics: { "HiSCR50": pct(42.5) }, placeboAdjustedDeltaMetrics: { "HiSCR50": pct(16.4) } },
            { dose: "300 mg Q2W", allMetrics: { "HiSCR50": pct(38.3) }, placeboAdjustedDeltaMetrics: { "HiSCR50": pct(12.2) } },
          ],
          allPlaceboMetrics: { "HiSCR50": pct(26.1) },
          note: "FDA-requested Week 16 analysis: Q4W was significant in SUNRISE; Q2W was numerically higher than placebo. Label allows escalation to Q2W for inadequate response.",
          publication: "SUNSHINE/SUNRISE Phase 3 publication; Cosentyx Prescribing Information",
          year: 2023,
        },
      ],
      aadLongTermObservedCase: {
        source: "AAD.pptx slide 8",
        timepoint: "Week 52",
        "SUNSHINE HiSCR75": pct(40),
        "SUNRISE HiSCR75": pct(44),
        "SUNSHINE HiSCR90": pct(25),
        "SUNRISE HiSCR90": pct(27),
        "SUNSHINE HiSCR100": pct(18),
        "SUNRISE HiSCR100": pct(19),
      },
      keyMessage: "First newer post-adalimumab HS biologic; efficacy is meaningful but AAD cross-trial long-term clearance appears below bimekizumab in observed-case comparisons.",
      confidence: "high",
      safetyBullets: ["No boxed warning", "Infection and Candida risk", "Evaluate for TB before initiation", "Caution/monitor for inflammatory bowel disease"],
      safetySignals: { BBW: "green", Infection: "yellow", Malignancy: "green", TB: "yellow", Monitoring: "yellow", IBD: "red" },
      sourceNotes: ["Cosentyx FDA label", "SUNSHINE/SUNRISE Phase 3 publication", "AAD.pptx slide 8"],
    },
    {
      name: "bimekizumab",
      brandName: "Bimzelx",
      drugClass: "IL-17A/F inhibitor",
      mechanism: "Dual inhibition of IL-17A and IL-17F.",
      route: "Subcutaneous",
      approvalYear: 2024,
      approvedIndication: "US: moderate-to-severe hidradenitis suppurativa in adults.",
      adultHsDose:
        "320 mg SC every 2 weeks through Week 16, then every 4 weeks; dosing details should be checked in the current label.",
      primaryEndpointLabel: "HiSCR50 at Week 16",
      overallResult: pct(50),
      metrics: { "HiSCR50": pct(50), "HiSCR75": pct(35), "HiSCR90 Week 48 observed-case range": "37-47", "HiSCR100 Week 48 observed-case range": "27-31", "IHS4-55": pct(56.4) },
      pivotalStudies: [
        {
          name: "BE HEARD I / Trial HS-1",
          phase: "Phase 3",
          n: 505,
          comparator: "placebo",
          regimen: "bimekizumab 320 mg Q2W induction arm highlighted in AAD deck",
          primaryEndpoint: "HiSCR50 at Week 16",
          timepoint: "Week 16",
          result: pct(48),
          placeboResult: pct(29),
          placeboAdjustedDelta: pct(19),
          allMetrics: { "HiSCR50": pct(48), "HiSCR75": pct(33), "IHS4-55 pooled Q2W-to-Q2W": pct(56.4), "IHS4 change from baseline": -17.8 },
          allPlaceboMetrics: { "HiSCR50": pct(29), "HiSCR75": pct(18), "IHS4-55 pooled placebo": pct(28.1), "IHS4 change from baseline": -6.1 },
          publication: "BE HEARD I/II Lancet publication; Bimzelx Prescribing Information",
          year: 2024,
        },
        {
          name: "BE HEARD II / Trial HS-2",
          phase: "Phase 3",
          n: 509,
          comparator: "placebo",
          regimen: "bimekizumab 320 mg Q2W induction arm highlighted in AAD deck",
          primaryEndpoint: "HiSCR50 at Week 16",
          timepoint: "Week 16",
          result: pct(52),
          placeboResult: pct(32),
          placeboAdjustedDelta: pct(20),
          allMetrics: { "HiSCR50": pct(52), "HiSCR75": pct(36), "IHS4-55 pooled Q2W-to-Q2W": pct(56.4), "IHS4 change from baseline": -18.1 },
          allPlaceboMetrics: { "HiSCR50": pct(32), "HiSCR75": pct(16), "IHS4-55 pooled placebo": pct(28.1), "IHS4 change from baseline": -7.3 },
          publication: "BE HEARD I/II Lancet publication; Bimzelx Prescribing Information",
          year: 2024,
        },
      ],
      aadLongTermObservedCase: {
        source: "AAD.pptx slide 8",
        timepoint: "Week 48",
        "BE HEARD I HiSCR75": pct(56),
        "BE HEARD II HiSCR75": pct(65),
        "BE HEARD I HiSCR90": pct(37),
        "BE HEARD II HiSCR90": pct(47),
        "BE HEARD I HiSCR100": pct(27),
        "BE HEARD II HiSCR100": pct(31),
      },
      keyMessage: "Current high-efficacy approved HS biologic benchmark in AAD cross-trial comparisons; dual IL-17A/F efficacy balanced by Candida/IBD/liver-warning considerations.",
      confidence: "high",
      safetyBullets: ["No boxed warning", "Higher Candida signal than single IL-17A blockade", "Evaluate for TB before initiation", "Warnings include liver biochemical abnormalities, suicidal ideation/behavior, infection, and inflammatory bowel disease"],
      safetySignals: { BBW: "green", Infection: "yellow", Malignancy: "green", TB: "yellow", Monitoring: "yellow", IBD: "red" },
      sourceNotes: ["Bimzelx FDA label", "BE HEARD I/II Phase 3 publication", "AAD.pptx slides 8 and 18"],
    },
  ],

  aad2026Updates: [
    {
      topic: "Povorcitinib Week 54 and TNF-alpha-experienced subgroup",
      asset: "povorcitinib",
      source: "AAD.pptx slides 7-13; Incyte 2025/2026 STOP-HS releases",
      summary:
        "STOP-HS1/2 Phase 3 met Week 12 HiSCR50 for both 45 mg and 75 mg QD doses. AAD slides show responses continuing to improve through Week 54 and provide TNF-alpha-experienced subgroup deltas.",
      week54ObservedCase: {
        "STOP-HS1 45 mg HiSCR75": pct(39.0),
        "STOP-HS1 75 mg HiSCR75": pct(47.5),
        "STOP-HS2 45 mg HiSCR75": pct(57.0),
        "STOP-HS2 75 mg HiSCR75": pct(46.8),
        "STOP-HS1 45 mg HiSCR90": pct(23.7),
        "STOP-HS1 75 mg HiSCR90": pct(28.8),
        "STOP-HS2 45 mg HiSCR90": pct(34.2),
        "STOP-HS2 75 mg HiSCR90": pct(29.8),
        "STOP-HS1 45 mg HiSCR100": pct(19.5),
        "STOP-HS1 75 mg HiSCR100": pct(22.0),
        "STOP-HS2 45 mg HiSCR100": pct(27.2),
        "STOP-HS2 75 mg HiSCR100": pct(21.0),
      },
      tnfExperiencedWeek12: {
        "45 mg HiSCR50 active": pct(39.0),
        "45 mg HiSCR50 placebo": pct(21.4),
        "45 mg HiSCR50 delta": pct(17.6),
        "75 mg HiSCR50 active": pct(36.3),
        "75 mg HiSCR50 placebo": pct(21.4),
        "75 mg HiSCR50 delta": pct(14.9),
        "45 mg HiSCR75 active": pct(19.5),
        "45 mg HiSCR75 placebo": pct(4.1),
        "45 mg HiSCR75 delta": pct(15.4),
        "75 mg HiSCR75 active": pct(22.1),
        "75 mg HiSCR75 placebo": pct(4.1),
        "75 mg HiSCR75 delta": pct(18.0),
      },
    },
    {
      topic: "Sonelokimab VELA Week 40",
      asset: "sonelokimab",
      source: "AAD.pptx slides 14-15; MoonLake 2025/2026 VELA releases",
      summary:
        "VELA-1 achieved the Week 16 HiSCR75 endpoint, while VELA-2 missed the composite primary endpoint with a high placebo response; Week 40 AAD update showed approximately 62% HiSCR75 and up to 32% HiSCR100.",
      week16: { "VELA-1 HiSCR75 delta": pct(17), "VELA-2 HiSCR75 delta": pct(9), "VELA-2 p value": 0.053 },
      week40: { "HiSCR75 approx": pct(62), "HiSCR100 up to": pct(32) },
    },
    {
      topic: "Lutikizumab and IHS4",
      asset: "lutikizumab",
      source: "AAD.pptx slides 16-18; AbbVie lutikizumab Phase 2/Phase 3 materials",
      summary:
        "AAD highlighted a biologic-naive single-arm open-label Phase 2 cohort with Week 16 LS mean IHS4 change from baseline of -19.3, HiSCR50 66.0%, and HiSCR75 46.8%; the controlled TNF-failure Phase 2 supports ongoing Phase 3 INTREPID.",
      biologicNaiveOpenLabel: { "HiSCR50": pct(66.0), "HiSCR75": pct(46.8), "IHS4 LS mean CFB": -19.3, n: 47 },
      tnfFailureControlled: { "Q2W HiSCR50 delta": pct(13.8), "Q2W HiSCR75 delta": pct(21.0), "QW HiSCR50 delta": pct(24.1), "QW HiSCR75 delta": pct(28.2) },
    },
    {
      topic: "Upadacitinib oral JAK1 HS signal",
      asset: "upadacitinib",
      source: "AAD.pptx slides 20-22; JAAD Phase 2 publication",
      summary:
        "AAD reported Week 12 IHS4-55 of 40.4% with upadacitinib 30 mg QD versus 19.0% placebo. HiSCR50 was 38.3% versus 23.8%. Phase 3 Step-Up HS is ongoing in prior biologic inadequate responders/intolerant patients.",
      phase2Week12: { "HiSCR50 active": pct(38.3), "HiSCR50 placebo": pct(23.8), "HiSCR50 delta": pct(14.7), "IHS4-55 active": pct(40.4), "IHS4-55 placebo": pct(19.0), "IHS4-55 delta": pct(21.4), "IHS4-75 delta": pct(25.5), "IHS4-90 delta": pct(12.8) },
    },
  ],

  lateStageAndPipeline: [
    {
      name: "povorcitinib",
      sponsor: "Incyte",
      drugClass: "Oral JAK1 inhibitor",
      mechanism: "Selective JAK1 inhibition.",
      route: "Oral",
      status: "Phase 3 positive; not FDA-approved for HS as of 2026-05-10",
      trialProgram: ["STOP-HS1", "STOP-HS2"],
      n: 1227,
      dosing: ["45 mg QD", "75 mg QD"],
      latestReadout:
        "Both pivotal STOP-HS studies met the Week 12 HiSCR50 primary endpoint; sponsor reported durable Week 54 responses and AAD showed biologic-experienced subgroup analyses.",
      keyMetrics: { "Week 54 HiSCR50 up to": pct(71.4), "Week 54 HiSCR75 up to": pct(57.0), "Week 54 HiSCR100 up to": pct(29.0), "ANdT=0 up to": pct(20.0) },
      confidence: "high for status; medium for cross-trial positioning",
      sourceNotes: ["Incyte STOP-HS press releases", "AAD.pptx slides 7-13"],
    },
    {
      name: "sonelokimab",
      sponsor: "MoonLake Immunotherapeutics",
      drugClass: "IL-17A/F nanobody with albumin-binding domain",
      mechanism: "Inhibits IL-17A and IL-17F; designed for tissue penetration and half-life extension.",
      route: "Subcutaneous",
      status: "Phase 3; not FDA-approved for HS as of 2026-05-10",
      trialProgram: ["VELA-1", "VELA-2", "VELA-TEEN"],
      latestReadout:
        "VELA-1 met Week 16 HiSCR75; VELA-2 missed the composite primary endpoint but supportive analyses and Week 40 durability were highlighted at AAD. MoonLake announced positive final pre-BLA FDA alignment in May 2026.",
      keyMetrics: { "Week 40 HiSCR75 approx": pct(62), "Week 40 HiSCR100 up to": pct(32) },
      confidence: "medium-high",
      sourceNotes: ["MoonLake VELA releases", "AAD.pptx slides 14-15"],
    },
    {
      name: "lutikizumab",
      sponsor: "AbbVie",
      drugClass: "Dual IL-1alpha / IL-1beta inhibitor",
      mechanism: "Blocks IL-1alpha and IL-1beta inflammatory signaling.",
      route: "Subcutaneous",
      status: "Phase 3 INTREPID ongoing; not approved",
      trialProgram: ["Phase 2 anti-TNF-failure study", "INTREPID Phase 3"],
      latestReadout:
        "Controlled TNF-failure Phase 2 supports development; AAD added biologic-naive open-label data with strong IHS4 and HiSCR response but no placebo arm.",
      keyMetrics: { "TNF-failure QW HiSCR50": pct(59.5), "TNF-failure placebo HiSCR50": pct(35.0), "Biologic-naive open-label HiSCR50": pct(66.0), "Biologic-naive open-label HiSCR75": pct(46.8) },
      confidence: "medium",
      sourceNotes: ["AbbVie Phase 2 materials", "AAD.pptx slides 16-18"],
    },
    {
      name: "upadacitinib",
      brandName: "Rinvoq",
      sponsor: "AbbVie",
      drugClass: "Oral JAK1 inhibitor",
      mechanism: "Selective JAK1 inhibition.",
      route: "Oral",
      status: "Phase 2 positive/Phase 3 ongoing in HS; approved for other inflammatory diseases but not HS as of 2026-05-10",
      trialProgram: ["Phase 2 HS", "Step-Up HS Phase 3"],
      latestReadout:
        "AAD emphasized IHS4-55, IHS4-75, and IHS4-90 as differentiating oral endpoints; Phase 3 Step-Up HS targets biologic inadequate responders/intolerant patients.",
      keyMetrics: { "HiSCR50 Week 12 active": pct(38.3), "HiSCR50 Week 12 placebo": pct(23.8), "IHS4-55 Week 12 active": pct(40.4), "IHS4-55 Week 12 placebo": pct(19.0) },
      confidence: "medium",
      sourceNotes: ["JAAD Phase 2 publication", "AAD.pptx slides 20-22"],
    },
    {
      name: "brivekimig",
      sponsor: "Sanofi",
      drugClass: "TNF-alpha x OX40L bispecific nanobody",
      mechanism: "Dual TNF-alpha and OX40L blockade.",
      route: "Subcutaneous or IV depending on development stage",
      status: "Phase 2a; not approved",
      trialProgram: ["HS-OBTAIN"],
      latestReadout:
        "AAD included HS-OBTAIN biologic-naive cross-trial values showing numerical separation from placebo, but this remains early and small compared with approved biologics.",
      keyMetrics: { "HiSCR50": pct(67), "HiSCR50 placebo": pct(37), "HiSCR75": pct(54), "HiSCR75 placebo": pct(22), "IHS4-55": pct(65), "IHS4-55 placebo": pct(35) },
      confidence: "low-medium",
      sourceNotes: ["AAD.pptx slides 18 and 49"],
    },
    {
      name: "NAV-240",
      sponsor: "Navigator Medicines",
      drugClass: "OX40L x TNF-alpha bispecific",
      mechanism: "Dual OX40L and TNF-alpha blockade.",
      route: "Intravenous in early studies",
      status: "Phase 2a MAINSAIL ongoing; not approved",
      trialProgram: ["Phase 1b MAD", "MAINSAIL Phase 2a HS"],
      latestReadout:
        "AAD highlighted Phase 1b safety/PK/PD and an ongoing N=150 Phase 2a HS study with HiSCR75 at Week 16; data expected in 2H 2027.",
      confidence: "low-medium",
      sourceNotes: ["AAD.pptx slide 49"],
    },
    {
      name: "NAV-242",
      sponsor: "Navigator Medicines",
      drugClass: "Half-life-extended OX40L x TNF-alpha bispecific",
      mechanism: "Next-generation OX40L/TNF-alpha bispecific designed for longer half-life and subcutaneous dosing.",
      route: "Subcutaneous planned/under study",
      status: "Phase 1; not approved",
      latestReadout:
        "AAD slide 50 described enhanced stability and extended PK versus NAV-240, with data expected 4Q 2026. The slide contains a route/half-life inconsistency, so this file records the qualitative direction only.",
      confidence: "low",
      sourceNotes: ["AAD.pptx slide 50"],
    },
    {
      name: "SAR445399",
      sponsor: "Sanofi",
      drugClass: "IL-1R3 antagonist",
      mechanism: "Targets IL-1 receptor accessory protein pathway biology.",
      route: "Not established for HS",
      status: "Early/preclinical or human challenge signal; not approved",
      latestReadout:
        "AAD executive summary referenced anti-inflammatory effects in LPS/IMQ challenge models; no HS efficacy data suitable for response-rate comparison.",
      confidence: "low",
      sourceNotes: ["AAD.pptx executive summary slide 5"],
    },
  ],

  correctionsAndBuildNotes: [
    "Created HS file de novo; no prior HS TypeScript file was provided in this turn.",
    "Focused approved-drug section on FDA-approved HS therapies: adalimumab, secukinumab, and bimekizumab; updated secukinumab to reflect 2026 pediatric 12+ HS expansion.",
    "Separated approved-label pivotal values from AAD cross-trial observed-case values and late-stage pipeline metrics.",
    "Added endpoint definitions for HiSCR and IHS4 because AAD.pptx explicitly emphasized IHS4-55 as an emerging endpoint.",
    "Added current 2026 AAD updates for povorcitinib, sonelokimab, lutikizumab, and upadacitinib, including TNF-experienced subgroup data where available.",
    "Flagged limitations: lutikizumab biologic-naive AAD results are single-arm; sonelokimab VELA-2 missed the composite primary endpoint; upadacitinib and povorcitinib are oral JAK-class assets requiring class-safety context; NAV-240/NAV-242/SAR445399 are early and not comparable with approved biologics.",
  ],
} as const;

export default hidradenitisSuppurativa;
