export const PSORIASIS_KEYWORDS = [
  "psoriasis", "pso", "plaque psoriasis", "pasi", "spga", "iga",
  "skyrizi", "risankizumab", "tremfya", "guselkumab", "ilumya", "tildrakizumab",
  "bimzelx", "bimekizumab", "cosentyx", "secukinumab", "taltz", "ixekizumab",
  "siliq", "brodalumab", "stelara", "ustekinumab", "sotyktu", "deucravacitinib",
  "otezla", "apremilast", "icotrokinra", "icotyde", "jnj-2113", "pn-235",
  "il-17", "il-17a", "il-17f", "il-17ra", "il-23", "il-23p19", "il-23r",
  "tyk2", "pde4", "il-12/23", "ork001", "orka-001", "oruka", "zasocitinib",
  "tak-279", "envudeucitinib", "esk-001", "dc-806", "navepdekinra", "ly4100504", "tirzepatide", "together-pso",
];

const pct = (value: number) => value;

const psoriasis = {
  condition: "Moderate-to-Severe Plaque Psoriasis",
  dataRevisionDate: "2026-05-10",
  evidenceStandard:
    "Fact-checked against AAD.pptx plus current FDA labels, prescribing information, pivotal Phase 3 publications, and 2026 company/AAD press releases available on 2026-05-10.",
  units: "All numeric efficacy values are percentages unless otherwise stated. Cross-trial comparisons are descriptive only.",
  primaryEndpoints: ["PASI 75", "PASI 90", "PASI 100", "IGA 0/1 or sPGA 0/1"],
  evidenceNotes: [
    "Pivotal psoriasis labels often use PASI 75 plus IGA/sPGA 0/1 as co-primary endpoints for older agents; newer IL-23/IL-17/oral IL-23R programs emphasize PASI 90 and complete clearance.",
    "The prior file mixed absolute active-arm rates, placebo-adjusted effects, and later maintenance results. This rewrite keeps active and comparator rates separate and labels the timepoint.",
    "Week 52 values are retained only when they were present in the AAD deck, prescribing information, or sponsor/publication sources; otherwise induction values are used.",
    "Icotrokinra was moved from pipeline to approved because it received FDA approval in 2026 for moderate-to-severe plaque psoriasis in adults and pediatric patients 12 years and older weighing at least 40 kg who are candidates for systemic therapy or phototherapy.",
  ],

  drugs: [
    {
      name: "risankizumab",
      brandName: "Skyrizi",
      drugClass: "IL-23p19",
      mechanism: "Selective anti-IL-23p19 monoclonal antibody; subcutaneous maintenance every 12 weeks after Week 0/4 loading.",
      route: "Subcutaneous",
      approvalYear: 2019,
      approvedIndication:
        "US: moderate-to-severe plaque psoriasis in adults who are candidates for systemic therapy or phototherapy; additional labeled indications include psoriatic arthritis, Crohn's disease, and ulcerative colitis.",
      primaryEndpointLabel: "PASI 90 and sPGA 0/1 at Week 16",
      overallResult: pct(75),
      metrics: { "PASI 75": pct(92), "PASI 90": pct(75), "PASI 100": pct(44), "IGA 0/1": pct(86) },
      trials: [
        {
          name: "ULTIMMA-1",
          phase: "Phase 3",
          n: 506,
          comparator: "placebo and ustekinumab",
          regimen: "risankizumab 150 mg SC at Weeks 0 and 4, then Q12W",
          primaryEndpoint: "PASI 90 and sPGA 0/1 at Week 16",
          result: pct(75),
          placeboResult: pct(5),
          allMetrics: { "PASI 75": pct(89), "PASI 90": pct(75), "PASI 100": pct(36), "IGA 0/1": pct(88) },
          allPlaceboMetrics: { "PASI 75": pct(8), "PASI 90": pct(5), "PASI 100": pct(0), "IGA 0/1": pct(8) },
          maintenanceMetrics: { "PASI 90 Week 52": pct(82), "PASI 100 Week 52": pct(56) },
          timepoint: "Week 16",
          publication: "ULTIMMA-1/2 Phase 3 publication; Skyrizi Prescribing Information",
          year: 2019,
        },
        {
          name: "ULTIMMA-2",
          phase: "Phase 3",
          n: 491,
          comparator: "placebo and ustekinumab",
          regimen: "risankizumab 150 mg SC at Weeks 0 and 4, then Q12W",
          primaryEndpoint: "PASI 90 and sPGA 0/1 at Week 16",
          result: pct(75),
          placeboResult: pct(2),
          allMetrics: { "PASI 75": pct(90), "PASI 90": pct(75), "PASI 100": pct(51), "IGA 0/1": pct(84) },
          allPlaceboMetrics: { "PASI 75": pct(5), "PASI 90": pct(2), "PASI 100": pct(2), "IGA 0/1": pct(5) },
          maintenanceMetrics: { "PASI 90 Week 52": pct(81), "PASI 100 Week 52": pct(60) },
          timepoint: "Week 16",
          publication: "ULTIMMA-1/2 Phase 3 publication; Skyrizi Prescribing Information",
          year: 2019,
        },
      ],
      keyMessage: "High-clearance IL-23 with Q12W maintenance; prior PASI 100 value corrected to Week 16 rather than Week 52.",
      confidence: "high",
      safetyBullets: ["No boxed warning", "Evaluate for TB before initiation", "Infection precautions", "No routine laboratory monitoring requirement in label"],
      safetySignals: { BBW: "green", Malignancy: "green", Infection: "green", "CV Risk": "green", Monitoring: "green", "IBD Risk": "green" },
      sourceNotes: ["Skyrizi FDA label", "ULTIMMA-1/2 pivotal publications"],
    },
    {
      name: "guselkumab",
      brandName: "Tremfya",
      drugClass: "IL-23p19",
      mechanism: "Selective anti-IL-23p19 monoclonal antibody; subcutaneous Week 0/4 loading and Q8W maintenance.",
      route: "Subcutaneous",
      approvalYear: 2017,
      approvedIndication:
        "US: moderate-to-severe plaque psoriasis in adults and pediatric patients 6 years and older weighing at least 40 kg who are candidates for systemic therapy or phototherapy; also labeled for psoriatic arthritis, ulcerative colitis, and Crohn's disease.",
      primaryEndpointLabel: "IGA 0/1 and PASI 90 at Week 16",
      overallResult: pct(72),
      metrics: { "PASI 75": pct(89), "PASI 90": pct(72), "PASI 100": pct(36), "IGA 0/1": pct(85) },
      trials: [
        {
          name: "VOYAGE-1",
          phase: "Phase 3",
          n: 837,
          comparator: "placebo and adalimumab",
          regimen: "guselkumab 100 mg SC at Weeks 0 and 4, then Q8W",
          primaryEndpoint: "IGA 0/1 and PASI 90 at Week 16",
          result: pct(73),
          placeboResult: pct(3),
          allMetrics: { "PASI 75": pct(91), "PASI 90": pct(73), "PASI 100": pct(37), "IGA 0/1": pct(85) },
          allPlaceboMetrics: { "PASI 75": pct(6), "PASI 90": pct(3), "PASI 100": pct(1), "IGA 0/1": pct(7) },
          timepoint: "Week 16",
          publication: "VOYAGE-1 Phase 3 publication; Tremfya Prescribing Information",
          year: 2017,
        },
        {
          name: "VOYAGE-2",
          phase: "Phase 3",
          n: 992,
          comparator: "placebo and adalimumab",
          regimen: "guselkumab 100 mg SC at Weeks 0 and 4, then Q8W",
          primaryEndpoint: "IGA 0/1 and PASI 90 at Week 16",
          result: pct(70),
          placeboResult: pct(2),
          allMetrics: { "PASI 75": pct(86), "PASI 90": pct(70), "PASI 100": pct(34), "IGA 0/1": pct(84) },
          allPlaceboMetrics: { "PASI 75": pct(8), "PASI 90": pct(2), "PASI 100": pct(1), "IGA 0/1": pct(8) },
          timepoint: "Week 16",
          publication: "VOYAGE-2 Phase 3 publication; Tremfya Prescribing Information",
          year: 2017,
        },
      ],
      keyMessage: "Q8W IL-23 option with current pediatric 6+ label expansion; VOYAGE-2 N corrected to 992.",
      confidence: "high",
      safetyBullets: ["No boxed warning", "Evaluate for TB before initiation", "Infection precautions", "No routine laboratory monitoring requirement in label"],
      safetySignals: { BBW: "green", Malignancy: "green", Infection: "green", "CV Risk": "green", Monitoring: "green", "IBD Risk": "green" },
      sourceNotes: ["Tremfya FDA label", "VOYAGE-1/2 pivotal publications"],
    },
    {
      name: "tildrakizumab",
      brandName: "Ilumya",
      drugClass: "IL-23p19",
      mechanism: "Selective anti-IL-23p19 monoclonal antibody; subcutaneous Week 0/4 loading and Q12W maintenance.",
      route: "Subcutaneous",
      approvalYear: 2018,
      approvedIndication: "US: adults with moderate-to-severe plaque psoriasis who are candidates for systemic therapy or phototherapy.",
      primaryEndpointLabel: "PASI 75 and PGA 0/1 at Week 12",
      overallResult: pct(63),
      metrics: { "PASI 75": pct(63), "PASI 90": pct(36), "PASI 100": pct(13), "IGA 0/1": pct(57) },
      trials: [
        {
          name: "reSURFACE 1 / Trial 2",
          phase: "Phase 3",
          n: 772,
          comparator: "placebo",
          regimen: "tildrakizumab 100 mg SC at Weeks 0 and 4, then Q12W",
          primaryEndpoint: "PASI 75 and PGA 0/1 at Week 12",
          result: pct(64),
          placeboResult: pct(6),
          allMetrics: { "PASI 75": pct(64), "PASI 90": pct(35), "PASI 100": pct(14), "IGA 0/1": pct(58) },
          allPlaceboMetrics: { "PASI 75": pct(6), "PASI 90": pct(3), "PASI 100": pct(1), "IGA 0/1": pct(7) },
          timepoint: "Week 12",
          publication: "reSURFACE Phase 3 publication; Ilumya Prescribing Information",
          year: 2017,
        },
        {
          name: "reSURFACE 2 / Trial 3",
          phase: "Phase 3",
          n: 1090,
          comparator: "placebo and etanercept",
          regimen: "tildrakizumab 100 mg SC at Weeks 0 and 4, then Q12W",
          primaryEndpoint: "PASI 75 and PGA 0/1 at Week 12",
          result: pct(61),
          placeboResult: pct(6),
          allMetrics: { "PASI 75": pct(61), "PASI 90": pct(39), "PASI 100": pct(12), "IGA 0/1": pct(55) },
          allPlaceboMetrics: { "PASI 75": pct(6), "PASI 90": pct(1), "PASI 100": pct(0), "IGA 0/1": pct(4) },
          timepoint: "Week 12",
          publication: "reSURFACE Phase 3 publication; Ilumya Prescribing Information",
          year: 2017,
        },
      ],
      keyMessage: "Q12W IL-23 with lower short-term PASI 90 than newer IL-23 options; useful where dosing simplicity and safety profile matter.",
      confidence: "high",
      safetyBullets: ["No boxed warning", "Evaluate for TB before initiation", "Infection precautions"],
      safetySignals: { BBW: "green", Malignancy: "green", Infection: "green", "CV Risk": "green", Monitoring: "green", "IBD Risk": "green" },
      sourceNotes: ["Ilumya FDA label", "reSURFACE pivotal publications"],
    },
    {
      name: "bimekizumab",
      brandName: "Bimzelx",
      drugClass: "IL-17A/F",
      mechanism: "Dual IL-17A and IL-17F inhibitor; plaque-psoriasis maintenance is Q8W after Week 16, with Q4W considered for patients at least 120 kg.",
      route: "Subcutaneous",
      approvalYear: 2023,
      approvedIndication:
        "US: adults with moderate-to-severe plaque psoriasis who are candidates for systemic therapy or phototherapy; also approved for psoriatic arthritis, axial spondyloarthritis, and adult hidradenitis suppurativa.",
      primaryEndpointLabel: "PASI 90 and IGA 0/1 at Week 16",
      overallResult: pct(88),
      metrics: { "PASI 75": pct(95), "PASI 90": pct(88), "PASI 100": pct(63), "IGA 0/1": pct(89) },
      trials: [
        {
          name: "BE VIVID / Trial Ps-1",
          phase: "Phase 3",
          n: 567,
          comparator: "placebo and ustekinumab",
          regimen: "bimekizumab 320 mg SC Q4W through Week 16, then label maintenance",
          primaryEndpoint: "PASI 90 and IGA 0/1 at Week 16",
          result: pct(85),
          placeboResult: pct(5),
          allMetrics: { "PASI 75": pct(93), "PASI 90": pct(85), "PASI 100": pct(59), "IGA 0/1": pct(84) },
          allPlaceboMetrics: { "PASI 75": pct(5), "PASI 90": pct(5), "PASI 100": pct(0), "IGA 0/1": pct(5) },
          timepoint: "Week 16",
          publication: "BE VIVID Phase 3 publication; Bimzelx Prescribing Information",
          year: 2021,
        },
        {
          name: "BE READY / Trial Ps-2",
          phase: "Phase 3",
          n: 435,
          comparator: "placebo",
          regimen: "bimekizumab 320 mg SC Q4W through Week 16, then maintenance/withdrawal design",
          primaryEndpoint: "PASI 90 and IGA 0/1 at Week 16",
          result: pct(91),
          placeboResult: pct(1),
          allMetrics: { "PASI 75": pct(97), "PASI 90": pct(91), "PASI 100": pct(68), "IGA 0/1": pct(93) },
          allPlaceboMetrics: { "PASI 75": pct(1), "PASI 90": pct(1), "PASI 100": pct(0), "IGA 0/1": pct(1) },
          timepoint: "Week 16",
          publication: "BE READY Phase 3 publication; Bimzelx Prescribing Information",
          year: 2021,
        },
        {
          name: "BE SURE",
          phase: "Phase 3",
          n: 478,
          comparator: "adalimumab",
          regimen: "bimekizumab 320 mg SC Q4W through Week 16; active-comparator study",
          primaryEndpoint: "PASI 90 and IGA 0/1 at Week 16",
          result: pct(86),
          placeboResult: null,
          allMetrics: { "PASI 75": pct(95), "PASI 90": pct(86), "PASI 100": pct(62), "IGA 0/1": pct(85) },
          allPlaceboMetrics: { "PASI 75": null, "PASI 90": null, "PASI 100": null, "IGA 0/1": null },
          timepoint: "Week 16",
          publication: "BE SURE Phase 3 publication",
          year: 2021,
        },
      ],
      keyMessage: "Very high complete-clearance biologic; prior file's Q4W maintenance phrasing corrected to the US plaque-psoriasis label maintenance regimen.",
      confidence: "high",
      safetyBullets: ["No boxed warning", "Higher oral candidiasis signal than single IL-17A blockade", "Evaluate for TB before initiation", "Avoid/use caution in inflammatory bowel disease", "Monitor liver enzymes per label in some indications"],
      safetySignals: { BBW: "green", Malignancy: "green", Infection: "yellow", "CV Risk": "green", Monitoring: "yellow", "IBD Risk": "yellow" },
      sourceNotes: ["Bimzelx FDA label", "BE VIVID/BE READY/BE SURE publications"],
    },
    {
      name: "secukinumab",
      brandName: "Cosentyx",
      drugClass: "IL-17A",
      mechanism: "IL-17A inhibitor; subcutaneous loading at Weeks 0-4 and Q4W plaque-psoriasis maintenance.",
      route: "Subcutaneous or intravenous depending on indication/label",
      approvalYear: 2015,
      approvedIndication:
        "US: moderate-to-severe plaque psoriasis in adults and pediatric patients 6 years and older who are candidates for systemic therapy or phototherapy; also labeled across PsA, AS, nr-axSpA, ERA, JPsA, and HS.",
      primaryEndpointLabel: "PASI 75 and IGA mod 2011 0/1 at Week 12",
      overallResult: pct(80),
      metrics: { "PASI 75": pct(80), "PASI 90": pct(57), "PASI 100": pct(27), "IGA 0/1": pct(64) },
      trials: [
        {
          name: "ERASURE",
          phase: "Phase 3",
          n: 738,
          comparator: "placebo",
          regimen: "secukinumab 300 mg SC at Weeks 0, 1, 2, 3, and 4, then Q4W",
          primaryEndpoint: "PASI 75 and IGA 0/1 at Week 12",
          result: pct(82),
          placeboResult: pct(5),
          allMetrics: { "PASI 75": pct(82), "PASI 90": pct(59), "PASI 100": pct(29), "IGA 0/1": pct(65) },
          allPlaceboMetrics: { "PASI 75": pct(5), "PASI 90": pct(1), "PASI 100": pct(0), "IGA 0/1": pct(3) },
          timepoint: "Week 12",
          publication: "ERASURE/FIXTURE NEJM publication; Cosentyx Prescribing Information",
          year: 2014,
        },
        {
          name: "FIXTURE",
          phase: "Phase 3",
          n: 1306,
          comparator: "placebo and etanercept",
          regimen: "secukinumab 300 mg SC at Weeks 0, 1, 2, 3, and 4, then Q4W",
          primaryEndpoint: "PASI 75 and IGA 0/1 at Week 12",
          result: pct(77),
          placeboResult: pct(5),
          allMetrics: { "PASI 75": pct(77), "PASI 90": pct(54), "PASI 100": pct(24), "IGA 0/1": pct(62) },
          allPlaceboMetrics: { "PASI 75": pct(5), "PASI 90": pct(2), "PASI 100": pct(0), "IGA 0/1": pct(2) },
          timepoint: "Week 12",
          publication: "ERASURE/FIXTURE NEJM publication; Cosentyx Prescribing Information",
          year: 2014,
        },
      ],
      keyMessage: "Fast IL-17A option with broad dermatology/rheumatology label; monitor IBD risk.",
      confidence: "high",
      safetyBullets: ["No boxed warning", "Candida and upper respiratory infections", "Caution in inflammatory bowel disease", "Evaluate for TB before initiation"],
      safetySignals: { BBW: "green", Malignancy: "green", Infection: "yellow", "CV Risk": "green", Monitoring: "yellow", "IBD Risk": "red" },
      sourceNotes: ["Cosentyx FDA label", "ERASURE/FIXTURE pivotal publication"],
    },
    {
      name: "ixekizumab",
      brandName: "Taltz",
      drugClass: "IL-17A",
      mechanism: "High-affinity IL-17A inhibitor; plaque psoriasis uses Q2W induction through Week 12 then Q4W maintenance.",
      route: "Subcutaneous",
      approvalYear: 2016,
      approvedIndication:
        "US: moderate-to-severe plaque psoriasis in adults and pediatric patients 6 years and older who are candidates for systemic therapy or phototherapy; also labeled for PsA, AS, and nr-axSpA.",
      primaryEndpointLabel: "PASI 75 and sPGA 0/1 at Week 12",
      overallResult: pct(89),
      metrics: { "PASI 75": pct(89), "PASI 90": pct(70), "PASI 100": pct(35), "IGA 0/1": pct(82) },
      trials: [
        {
          name: "UNCOVER-1",
          phase: "Phase 3",
          n: 1296,
          comparator: "placebo",
          regimen: "ixekizumab 160 mg loading dose, then 80 mg Q2W through Week 12",
          primaryEndpoint: "PASI 75 and sPGA 0/1 at Week 12",
          result: pct(89),
          placeboResult: pct(4),
          allMetrics: { "PASI 75": pct(89), "PASI 90": pct(71), "PASI 100": pct(35), "IGA 0/1": pct(82) },
          allPlaceboMetrics: { "PASI 75": pct(4), "PASI 90": pct(1), "PASI 100": pct(0), "IGA 0/1": pct(3) },
          timepoint: "Week 12",
          publication: "UNCOVER pivotal publication; Taltz Prescribing Information",
          year: 2016,
        },
        {
          name: "UNCOVER-2",
          phase: "Phase 3",
          n: 1224,
          comparator: "placebo and etanercept",
          regimen: "ixekizumab 160 mg loading dose, then 80 mg Q2W through Week 12",
          primaryEndpoint: "PASI 75 and sPGA 0/1 at Week 12",
          result: pct(90),
          placeboResult: pct(2),
          allMetrics: { "PASI 75": pct(90), "PASI 90": pct(71), "PASI 100": pct(40), "IGA 0/1": pct(83) },
          allPlaceboMetrics: { "PASI 75": pct(2), "PASI 90": pct(1), "PASI 100": pct(0), "IGA 0/1": pct(2) },
          timepoint: "Week 12",
          publication: "UNCOVER pivotal publication; Taltz Prescribing Information",
          year: 2016,
        },
        {
          name: "UNCOVER-3",
          phase: "Phase 3",
          n: 1346,
          comparator: "placebo and etanercept",
          regimen: "ixekizumab 160 mg loading dose, then 80 mg Q2W through Week 12",
          primaryEndpoint: "PASI 75 and sPGA 0/1 at Week 12",
          result: pct(87),
          placeboResult: pct(7),
          allMetrics: { "PASI 75": pct(87), "PASI 90": pct(68), "PASI 100": pct(37), "IGA 0/1": pct(80) },
          allPlaceboMetrics: { "PASI 75": pct(7), "PASI 90": pct(3), "PASI 100": pct(0), "IGA 0/1": pct(7) },
          timepoint: "Week 12",
          publication: "UNCOVER pivotal publication; Taltz Prescribing Information",
          year: 2016,
        },
      ],
      keyMessage: "Rapid-onset IL-17A option; AAD 2026 also highlighted Phase 3b TOGETHER-PsO with tirzepatide in obesity/overweight.",
      confidence: "high",
      safetyBullets: ["No boxed warning", "Candida and injection-site reactions", "Caution in inflammatory bowel disease", "Evaluate for TB before initiation"],
      safetySignals: { BBW: "green", Malignancy: "green", Infection: "yellow", "CV Risk": "green", Monitoring: "yellow", "IBD Risk": "red" },
      sourceNotes: ["Taltz FDA label", "UNCOVER pivotal publication", "AAD.pptx TOGETHER-PsO slide"],
    },
    {
      name: "brodalumab",
      brandName: "Siliq",
      drugClass: "IL-17RA",
      mechanism: "IL-17 receptor A antagonist; blocks signaling by multiple IL-17 cytokines including IL-17A and IL-17F.",
      route: "Subcutaneous",
      approvalYear: 2017,
      approvedIndication:
        "US: adults with moderate-to-severe plaque psoriasis who are candidates for systemic therapy or phototherapy and have failed to respond or have lost response to other systemic therapies.",
      primaryEndpointLabel: "PASI 75 and sPGA 0/1 at Week 12",
      overallResult: pct(84),
      metrics: { "PASI 75": pct(84), "PASI 90": pct(69), "PASI 100": pct(42), "IGA 0/1": pct(77) },
      trials: [
        {
          name: "AMAGINE-1",
          phase: "Phase 3",
          n: 661,
          comparator: "placebo",
          regimen: "brodalumab 210 mg SC at Weeks 0, 1, and 2, then Q2W",
          primaryEndpoint: "PASI 75 and sPGA 0/1 at Week 12",
          result: pct(83),
          placeboResult: pct(3),
          allMetrics: { "PASI 75": pct(83), "PASI 90": pct(70), "PASI 100": pct(42), "IGA 0/1": pct(76) },
          allPlaceboMetrics: { "PASI 75": pct(3), "PASI 90": pct(1), "PASI 100": pct(0), "IGA 0/1": pct(1) },
          timepoint: "Week 12",
          publication: "AMAGINE pivotal publication; Siliq Prescribing Information",
          year: 2015,
        },
        {
          name: "AMAGINE-2",
          phase: "Phase 3",
          n: 1831,
          comparator: "placebo and ustekinumab",
          regimen: "brodalumab 210 mg SC at Weeks 0, 1, and 2, then Q2W",
          primaryEndpoint: "PASI 75 and sPGA 0/1 at Week 12; PASI 100 vs ustekinumab as key complete-clearance endpoint",
          result: pct(86),
          placeboResult: pct(8),
          allMetrics: { "PASI 75": pct(86), "PASI 90": pct(70), "PASI 100": pct(44), "IGA 0/1": pct(79) },
          allPlaceboMetrics: { "PASI 75": pct(8), "PASI 90": pct(3), "PASI 100": pct(1), "IGA 0/1": pct(4) },
          timepoint: "Week 12",
          publication: "AMAGINE pivotal publication; Siliq Prescribing Information",
          year: 2015,
        },
        {
          name: "AMAGINE-3",
          phase: "Phase 3",
          n: 1881,
          comparator: "placebo and ustekinumab",
          regimen: "brodalumab 210 mg SC at Weeks 0, 1, and 2, then Q2W",
          primaryEndpoint: "PASI 75 and sPGA 0/1 at Week 12; PASI 100 vs ustekinumab as key complete-clearance endpoint",
          result: pct(85),
          placeboResult: pct(6),
          allMetrics: { "PASI 75": pct(85), "PASI 90": pct(69), "PASI 100": pct(37), "IGA 0/1": pct(80) },
          allPlaceboMetrics: { "PASI 75": pct(6), "PASI 90": pct(3), "PASI 100": pct(1), "IGA 0/1": pct(4) },
          timepoint: "Week 12",
          publication: "AMAGINE pivotal publication; Siliq Prescribing Information",
          year: 2015,
        },
      ],
      keyMessage: "Very high IL-17-pathway efficacy but label use is constrained by suicidal ideation/behavior boxed warning and REMS; prior primary-endpoint label corrected.",
      confidence: "high",
      safetyBullets: ["Boxed warning for suicidal ideation and behavior", "SILIQ REMS required", "Caution in inflammatory bowel disease", "Candida/infection precautions"],
      safetySignals: { BBW: "red", Malignancy: "green", Infection: "yellow", "CV Risk": "green", Monitoring: "red", "IBD Risk": "red" },
      sourceNotes: ["Siliq FDA label", "AMAGINE pivotal publications"],
    },
    {
      name: "ustekinumab",
      brandName: "Stelara",
      drugClass: "IL-12/23p40",
      mechanism: "Anti-p40 monoclonal antibody inhibiting IL-12 and IL-23; weight-based SC dosing with Q12W maintenance after Week 0/4 loading.",
      route: "Subcutaneous for psoriasis",
      approvalYear: 2009,
      approvedIndication:
        "US: moderate-to-severe plaque psoriasis in adults and pediatric patients 6 years and older who are candidates for systemic therapy or phototherapy; also labeled for psoriatic arthritis and inflammatory bowel disease indications.",
      primaryEndpointLabel: "PASI 75 at Week 12",
      overallResult: pct(67),
      metrics: { "PASI 75": pct(67), "PASI 90": pct(42), "PASI 100": pct(12), "IGA 0/1": pct(65) },
      trials: [
        {
          name: "PHOENIX-1",
          phase: "Phase 3",
          n: 766,
          comparator: "placebo",
          regimen: "ustekinumab 45 mg or 90 mg SC at Weeks 0 and 4, then Q12W; dose is weight-based in label",
          primaryEndpoint: "PASI 75 at Week 12",
          result: pct(67),
          placeboResult: pct(3),
          allMetrics: { "PASI 75": pct(67), "PASI 90": pct(42), "PASI 100": pct(12), "IGA 0/1": pct(65) },
          allPlaceboMetrics: { "PASI 75": pct(3), "PASI 90": pct(2), "PASI 100": pct(1), "IGA 0/1": pct(4) },
          timepoint: "Week 12",
          publication: "PHOENIX pivotal publication; Stelara Prescribing Information",
          year: 2008,
        },
        {
          name: "PHOENIX-2",
          phase: "Phase 3",
          n: 1230,
          comparator: "placebo",
          regimen: "ustekinumab 45 mg or 90 mg SC at Weeks 0 and 4, then Q12W; dose is weight-based in label",
          primaryEndpoint: "PASI 75 at Week 12",
          result: pct(67),
          placeboResult: pct(4),
          allMetrics: { "PASI 75": pct(67), "PASI 90": pct(42), "PASI 100": pct(12), "IGA 0/1": pct(66) },
          allPlaceboMetrics: { "PASI 75": pct(4), "PASI 90": pct(1), "PASI 100": pct(0), "IGA 0/1": pct(3) },
          timepoint: "Week 12",
          publication: "PHOENIX pivotal publication; Stelara Prescribing Information",
          year: 2008,
        },
      ],
      keyMessage: "Legacy IL-12/23 option with long safety history; no longer a high-clearance benchmark versus IL-23p19 and IL-17 agents.",
      confidence: "high",
      safetyBullets: ["No boxed warning", "Infection and malignancy precautions", "Evaluate for TB before initiation"],
      safetySignals: { BBW: "green", Malignancy: "yellow", Infection: "green", "CV Risk": "green", Monitoring: "green", "IBD Risk": "green" },
      sourceNotes: ["Stelara FDA label", "PHOENIX pivotal publications"],
    },
    {
      name: "icotrokinra",
      brandName: "Icotyde",
      aliases: ["JNJ-2113", "PN-235"],
      drugClass: "Oral IL-23R peptide antagonist",
      mechanism: "Targeted oral peptide that blocks IL-23 receptor signaling.",
      route: "Oral",
      approvalYear: 2026,
      approvedIndication:
        "US: moderate-to-severe plaque psoriasis in adults and pediatric patients 12 years and older weighing at least 40 kg who are candidates for systemic therapy or phototherapy.",
      primaryEndpointLabel: "IGA 0/1 and PASI 90 at Week 16; superiority to deucravacitinib assessed at Week 24 in ICONIC-ADVANCE",
      overallResult: pct(56),
      metrics: { "PASI 75": null, "PASI 90": pct(56), "PASI 100": pct(32), "IGA 0/1": pct(69) },
      trials: [
        {
          name: "ICONIC-ADVANCE 1",
          phase: "Phase 3",
          n: 754,
          comparator: "placebo and deucravacitinib",
          regimen: "icotrokinra 200 mg PO once daily",
          primaryEndpoint: "IGA 0/1 and PASI 90 at Week 16",
          result: pct(55),
          placeboResult: pct(4),
          allMetrics: { "PASI 75": null, "PASI 90": pct(55), "PASI 100": pct(31), "IGA 0/1": pct(68), "IGA 0": pct(37) },
          allPlaceboMetrics: { "PASI 75": null, "PASI 90": pct(4), "PASI 100": pct(1), "IGA 0/1": pct(11), "IGA 0": pct(2) },
          activeComparatorMetrics: { comparator: "deucravacitinib", "PASI 90 Week 16": pct(30), "IGA 0/1 Week 16": pct(50), "PASI 90 Week 24": pct(41), "IGA 0/1 Week 24": pct(52) },
          week24Metrics: { "PASI 90": pct(66), "PASI 100": pct(41), "IGA 0/1": pct(74), "IGA 0": pct(48) },
          week52Metrics: { "PASI 90": pct(71), "PASI 100": pct(49), "IGA 0/1": pct(75), "IGA 0": pct(52) },
          timepoint: "Week 16",
          publication: "Icotyde Prescribing Information; ICONIC-ADVANCE AAD 2026 presentation",
          year: 2026,
        },
        {
          name: "ICONIC-ADVANCE 2",
          phase: "Phase 3",
          n: 749,
          comparator: "placebo and deucravacitinib",
          regimen: "icotrokinra 200 mg PO once daily",
          primaryEndpoint: "IGA 0/1 and PASI 90 at Week 16",
          result: pct(57),
          placeboResult: pct(1),
          allMetrics: { "PASI 75": null, "PASI 90": pct(57), "PASI 100": pct(32), "IGA 0/1": pct(70), "IGA 0": pct(37) },
          allPlaceboMetrics: { "PASI 75": null, "PASI 90": pct(1), "PASI 100": pct(1), "IGA 0/1": pct(9), "IGA 0": pct(1) },
          activeComparatorMetrics: { comparator: "deucravacitinib", "PASI 90 Week 16": pct(34), "IGA 0/1 Week 16": pct(55), "PASI 90 Week 24": pct(43), "IGA 0/1 Week 24": pct(55) },
          week24Metrics: { "PASI 90": pct(65), "PASI 100": pct(33), "IGA 0/1": pct(68), "IGA 0": pct(40) },
          week52Metrics: { "PASI 90": pct(74), "PASI 100": pct(48), "IGA 0/1": pct(79), "IGA 0": pct(50) },
          timepoint: "Week 16",
          publication: "Icotyde Prescribing Information; ICONIC-ADVANCE AAD 2026 presentation",
          year: 2026,
        },
      ],
      keyMessage: "Newly approved first-in-class oral IL-23R peptide; AAD deck shows maintenance/deepening through Week 52 and catch-up after crossover from placebo or deucravacitinib.",
      confidence: "high",
      safetyBullets: ["No boxed warning", "Infection warning", "Serious infections were uncommon in 16-week placebo-controlled trials", "Label recommends vaccination/evaluation before use"],
      safetySignals: { BBW: "green", Malignancy: "green", Infection: "green", "CV Risk": "green", Monitoring: "green", "IBD Risk": "green" },
      sourceNotes: ["Icotyde FDA label", "AAD.pptx slides 42-45", "J&J 2026 FDA approval release"],
    },
    {
      name: "deucravacitinib",
      brandName: "Sotyktu",
      drugClass: "TYK2",
      mechanism: "Allosteric TYK2 inhibitor; oral once daily.",
      route: "Oral",
      approvalYear: 2022,
      approvedIndication: "US: adults with moderate-to-severe plaque psoriasis who are candidates for systemic therapy or phototherapy.",
      primaryEndpointLabel: "PASI 75 and sPGA 0/1 at Week 16",
      overallResult: pct(56),
      metrics: { "PASI 75": pct(56), "PASI 90": pct(34), "PASI 100": pct(14), "IGA 0/1": pct(52) },
      trials: [
        {
          name: "POETYK PSO-1",
          phase: "Phase 3",
          n: 666,
          comparator: "placebo and apremilast",
          regimen: "deucravacitinib 6 mg PO once daily",
          primaryEndpoint: "PASI 75 and sPGA 0/1 at Week 16",
          result: pct(58.4),
          placeboResult: pct(12.7),
          allMetrics: { "PASI 75": pct(58.4), "PASI 90": pct(35), "PASI 100": pct(14), "IGA 0/1": pct(53.6) },
          allPlaceboMetrics: { "PASI 75": pct(12.7), "PASI 90": pct(4), "PASI 100": pct(1), "IGA 0/1": pct(7.2) },
          activeComparatorMetrics: { comparator: "apremilast", "PASI 75": pct(35.1), "IGA 0/1": pct(32.1) },
          timepoint: "Week 16",
          publication: "Sotyktu Prescribing Information; POETYK PSO-1/2 publication",
          year: 2022,
        },
        {
          name: "POETYK PSO-2",
          phase: "Phase 3",
          n: 674,
          comparator: "placebo and apremilast",
          regimen: "deucravacitinib 6 mg PO once daily",
          primaryEndpoint: "PASI 75 and sPGA 0/1 at Week 16",
          result: pct(53.6),
          placeboResult: pct(9.4),
          allMetrics: { "PASI 75": pct(53.6), "PASI 90": pct(32), "PASI 100": pct(13), "IGA 0/1": pct(49.5) },
          allPlaceboMetrics: { "PASI 75": pct(9.4), "PASI 90": pct(4), "PASI 100": pct(1), "IGA 0/1": pct(8.6) },
          activeComparatorMetrics: { comparator: "apremilast", "PASI 75": pct(40.2), "IGA 0/1": pct(34.3) },
          timepoint: "Week 16",
          publication: "Sotyktu Prescribing Information; POETYK PSO-1/2 publication",
          year: 2022,
        },
      ],
      keyMessage: "First approved oral TYK2; placebo rates corrected from the prior file. AAD 2026 positions icotrokinra above deucravacitinib on Week 24 response.",
      confidence: "high",
      safetyBullets: ["No boxed warning", "Infections and viral reactivation warning", "Label includes malignancy and laboratory-abnormality warnings", "Avoid use with other potent immunosuppressants"],
      safetySignals: { BBW: "green", Malignancy: "yellow", Infection: "yellow", "CV Risk": "yellow", Monitoring: "yellow", "IBD Risk": "green" },
      sourceNotes: ["Sotyktu FDA label", "POETYK PSO-1/2 pivotal publication"],
    },
    {
      name: "apremilast",
      brandName: "Otezla",
      drugClass: "PDE4",
      mechanism: "Oral PDE4 inhibitor; titrated to 30 mg twice daily in adults with normal renal function.",
      route: "Oral",
      approvalYear: 2014,
      approvedIndication:
        "US: adults and pediatric patients 6 years and older and weighing at least 20 kg with moderate-to-severe plaque psoriasis who are candidates for phototherapy or systemic therapy; also labeled for psoriatic arthritis and oral ulcers associated with Behcet's disease.",
      primaryEndpointLabel: "PASI 75 at Week 16",
      overallResult: pct(31),
      metrics: { "PASI 75": pct(31), "PASI 90": null, "PASI 100": null, "IGA 0/1": pct(21) },
      trials: [
        {
          name: "ESTEEM 1",
          phase: "Phase 3",
          n: 844,
          comparator: "placebo",
          regimen: "apremilast 30 mg PO twice daily after titration",
          primaryEndpoint: "PASI 75 at Week 16",
          result: pct(33.1),
          placeboResult: pct(5.3),
          allMetrics: { "PASI 75": pct(33.1), "PASI 90": null, "PASI 100": null, "IGA 0/1": pct(21.7) },
          allPlaceboMetrics: { "PASI 75": pct(5.3), "PASI 90": null, "PASI 100": null, "IGA 0/1": pct(3.9) },
          timepoint: "Week 16",
          publication: "Otezla Prescribing Information; ESTEEM pivotal publication",
          year: 2015,
        },
        {
          name: "ESTEEM 2",
          phase: "Phase 3",
          n: 413,
          comparator: "placebo",
          regimen: "apremilast 30 mg PO twice daily after titration",
          primaryEndpoint: "PASI 75 at Week 16",
          result: pct(28.8),
          placeboResult: pct(5.8),
          allMetrics: { "PASI 75": pct(28.8), "PASI 90": null, "PASI 100": null, "IGA 0/1": pct(20.4) },
          allPlaceboMetrics: { "PASI 75": pct(5.8), "PASI 90": null, "PASI 100": null, "IGA 0/1": pct(4.4) },
          timepoint: "Week 16",
          publication: "Otezla Prescribing Information; ESTEEM pivotal publication",
          year: 2015,
        },
      ],
      keyMessage: "Lower-efficacy oral option with no biologic-screening burden; prior unsupported PASI 90/100 values removed.",
      confidence: "high",
      safetyBullets: ["No boxed warning", "GI adverse events early in treatment", "Depression warning", "Weight decrease warning", "Dose adjustment in severe renal impairment"],
      safetySignals: { BBW: "green", Malignancy: "green", Infection: "green", "CV Risk": "green", Monitoring: "green", "IBD Risk": "green" },
      sourceNotes: ["Otezla FDA label", "ESTEEM pivotal publications"],
    },
  ],

  aad2026Updates: [
    {
      topic: "Icotrokinra durability and complete clearance",
      source: "AAD.pptx slides 42-45; FDA label; J&J approval release",
      summary:
        "ICONIC-ADVANCE 1/2 showed Week 16 superiority versus placebo and Week 24 superiority versus deucravacitinib, with IGA 0/1 and PASI 90 maintained or deepened through Week 52 in the continuous-icotrokinra arms.",
      metrics: {
        "ADVANCE 1 IGA 0/1 Week 16": pct(68),
        "ADVANCE 1 PASI 90 Week 16": pct(55),
        "ADVANCE 1 PASI 90 Week 52": pct(71),
        "ADVANCE 2 IGA 0/1 Week 16": pct(70),
        "ADVANCE 2 PASI 90 Week 16": pct(57),
        "ADVANCE 2 PASI 90 Week 52": pct(74),
      },
    },
    {
      topic: "Ixekizumab plus tirzepatide in psoriasis with obesity/overweight",
      source: "AAD.pptx slide 46; Lilly TOGETHER-PsO press release",
      summary:
        "TOGETHER-PsO met the simultaneous skin-clearance and weight-loss primary endpoint at Week 36: PASI 100 plus at least 10% weight reduction was 27.1% with ixekizumab plus tirzepatide versus 5.8% with ixekizumab alone; PASI 100 alone was 40.6% versus 29.0%.",
      metrics: { "PASI 100 + >=10% weight loss": pct(27.1), "Ixekizumab alone comparator": pct(5.8), "PASI 100 combo": pct(40.6), "PASI 100 ixekizumab alone": pct(29.0) },
      note: "This is not a new psoriasis drug approval; it is a comorbidity/weight-loss combination strategy.",
    },
  ],

  emerging: [
    {
      name: "zasocitinib",
      aliases: ["TAK-279"],
      company: "Takeda",
      drugClass: "TYK2",
      mechanism: "Next-generation selective oral TYK2 inhibitor.",
      tier: "late-stage",
      phase: "Phase 3 positive; not approved",
      indication: "Moderate-to-severe plaque psoriasis",
      primaryMetric: "sPGA 0/1",
      primaryMetricValue: pct(70),
      placeboValue: null,
      timepoint: "Week 16",
      trialName: "LATITUDE 1 / LATITUDE 2",
      n: 1801,
      metrics: { "sPGA 0/1 Week 16 approx": pct(70), "PASI 75 early separation": "significant by Week 4 per sponsor" },
      safetySignals: { BBW: "gray", Malignancy: "gray", Infection: "gray", "CV Risk": "gray", Monitoring: "gray", "IBD Risk": "gray" },
      safetyBullets: ["No new safety signals in Phase 3 press release", "Full peer-reviewed safety table pending"],
      keyInsight: "Prior file incorrectly listed Acelyrin and a BID dose. The current sponsor is Takeda, dosing is once daily, and Phase 3 data are positive.",
      source: "Takeda March 2026 Phase 3/AAD release",
      sourceYear: 2026,
    },
    {
      name: "envudeucitinib",
      aliases: ["ESK-001"],
      company: "Alumis",
      drugClass: "TYK2",
      mechanism: "Highly selective oral allosteric TYK2 inhibitor.",
      tier: "late-stage",
      phase: "Phase 3 positive; not approved",
      indication: "Moderate-to-severe plaque psoriasis",
      primaryMetric: "PASI 75 and sPGA 0/1",
      primaryMetricValue: null,
      placeboValue: null,
      timepoint: "Week 16 and Week 24",
      trialName: "ONWARD 1 / ONWARD 2",
      n: 1700,
      metrics: { "PASI 90 Week 24 ONWARD 1": pct(68.0), "PASI 90 Week 24 ONWARD 2": pct(62.1), "PASI 100 Week 24 ONWARD 1": pct(41.0), "PASI 100 Week 24 ONWARD 2": pct(39.5) },
      safetySignals: { BBW: "gray", Malignancy: "gray", Infection: "gray", "CV Risk": "gray", Monitoring: "gray", "IBD Risk": "gray" },
      safetyBullets: ["Phase 3 safety/tolerability described by sponsor as favorable and consistent with Phase 2", "Full label-level characterization pending"],
      keyInsight: "Prior file incorrectly named Arcutis as sponsor. Envudeucitinib is an Alumis asset with positive ONWARD Phase 3 results.",
      source: "Alumis March 2026 ONWARD/AAD release",
      sourceYear: 2026,
    },

{
      name: "ORKA-001",
      company: "Oruka Therapeutics",
      drugClass: "IL-23p19",
      mechanism: "Long-acting anti-IL-23p19 antibody engineered for very infrequent maintenance dosing.",
      tier: "mid-stage",
      phase: "Phase 2a; not approved",
      indication: "Moderate-to-severe plaque psoriasis",
      primaryMetric: "PASI 100",
      primaryMetricValue: pct(63.5),
      placeboValue: pct(4.8),
      metrics: {
        "PASI 75":  pct(93.7),
        "PASI 90":  pct(82.5),
        "PASI 100": pct(63.5),
        "IGA 0/1":  pct(76.2),
      },
      placeboMetrics: {
        "PASI 75":  pct(9.5),
        "PASI 90":  pct(4.8),
        "PASI 100": pct(4.8),
        "IGA 0/1":  pct(4.8),
      },
      timepoint: "Week 16",
      trialName: "EVERLAST-A Phase 2a",
      n: 84,
      keyInsight: "EVERLAST-A Phase 2a: PASI 100 of 63.5% at Week 16, competitive with approved IL-23p19 biologics. Infrequent dosing (quarterly or less) is the key differentiation thesis vs risankizumab, guselkumab.",
      safetySignals: { BBW: "gray", Malignancy: "gray", Infection: "gray", "CV Risk": "gray", Monitoring: "gray", "IBD Risk": "gray" },
      safetyBullets: [
        "Sponsor described safety as favorable and consistent with IL-23p19 class",
        "Phase 2a only; Phase 3 confirmation needed. TEAEs comparable between active and PBO",
      ],
      source: "Oruka April 2026 EVERLAST-A press release",
      sourceUrl: "https://www.globenewswire.com/news-release/2026/04/27/3281468/0/en/oruka-therapeutics-announces-positive-week-16-data-for-orka-001-from-the-ongoing-everlast-a-phase-2a-trial-in-moderate-to-severe-plaque-psoriasis.html",
      sourceYear: 2026,
    },
    
    {
      name: "navepdekinra",
      aliases: ["DC-806", "LY4100504"],
      company: "Eli Lilly / Dice heritage program",
      drugClass: "Oral IL-17-pathway small molecule",
      mechanism: "Oral small molecule designed to inhibit IL-17 signaling biology; the prior CCR6/Dermavant mechanism was not supported.",
      tier: "watchlist",
      phase: "Phase 1c published; not approved",
      indication: "Mild-to-moderate plaque psoriasis in early proof-of-concept study",
      primaryMetric: "Mean PASI percent reduction",
      primaryMetricValue: pct(43.7),
      placeboValue: pct(13.3),
      timepoint: "Day 29",
      trialName: "Phase 1c proof-of-concept",
      n: 32,
      metrics: { "PASI percent reduction 800 mg BID": pct(43.7), "PASI percent reduction 200 mg BID": pct(15.1), "placebo PASI percent reduction": pct(13.3) },
      safetySignals: { BBW: "gray", Malignancy: "gray", Infection: "gray", "CV Risk": "gray", Monitoring: "gray", "IBD Risk": "gray" },
      safetyBullets: ["Very small and short Phase 1c study", "No serious adverse events or treatment-related discontinuations reported in the publication", "Needs Phase 2 confirmation"],
      keyInsight: "Corrected from the prior CCR6/Dermavant entry. This is an early oral IL-17-pathway asset and should not be compared with Phase 3 or approved drugs.",
      source: "Phase 1c publication / Lilly-Dice program update",
      sourceYear: 2026,
    },
  ],

  correctionsApplied: [
    "Moved icotrokinra/Icotyde from emerging pipeline to approved therapy and added FDA-approved indication, dosing, ICONIC-ADVANCE 1/2, Week 24 deucravacitinib comparison, and Week 52 AAD durability values.",
    "Corrected risankizumab PASI 100: prior file used Week 52 values as if they were Week 16 values. Week 16 PASI 100 is recorded as 36% in ULTIMMA-1 and 51% in ULTIMMA-2; Week 52 values are separately recorded.",
    "Corrected guselkumab VOYAGE-2 sample size and updated current pediatric 6+ / at least 40 kg label expansion.",
    "Corrected bimekizumab plaque-psoriasis maintenance from continuous Q4W to label maintenance Q8W after Week 16, with Q4W considered for patients at least 120 kg.",
    "Corrected brodalumab primary endpoint label from PASI 100/IGA 0 to PASI 75 and sPGA 0/1; retained PASI 100 as a complete-clearance endpoint.",
    "Corrected deucravacitinib placebo values using POETYK label values and clarified label safety warnings.",
    "Removed unsupported apremilast PASI 90/PASI 100 values and kept label-supported PASI 75 and sPGA/IGA response.",
    "Corrected pipeline sponsor/status errors: zasocitinib is Takeda and Phase 3 positive; envudeucitinib is Alumis and Phase 3 positive; ORKA-001 data are from EVERLAST-A, not ORION.",
    "Corrected DC-806 to navepdekinra/LY4100504 as an oral IL-17-pathway small molecule rather than a CCR6/Dermavant program.",
    "Removed povorcitinib from psoriasis keywords because the AAD deck discusses povorcitinib in hidradenitis suppurativa, not psoriasis.",
    "Added AAD 2026 TOGETHER-PsO ixekizumab plus tirzepatide update as a comorbidity/combination strategy rather than a new psoriasis approval.",
  ],
} as const;

export default psoriasis;
